// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension Interpreter {
    func registerGeneratedStdlib(into i: Interpreter) {
        i.registerComputed(on: "String", name: "localizedCapitalized") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.localizedCapitalized)
        }

        i.registerComputed(on: "String", name: "localizedLowercase") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.localizedLowercase)
        }

        i.registerComputed(on: "String", name: "localizedUppercase") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.localizedUppercase)
        }

        i.registerComputed(on: "String", name: "capitalized") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.capitalized)
        }

        i.registerStaticValue(on: "Int", name: "zero", value: .int(Int.zero))

        i.registerComputed(on: "Int", name: "description") { receiver in
            let recv: Int = try unboxInt(receiver)
            return .string(recv.description)
        }

        i.registerInit(on: "Int", labels: []) { args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("Int(): expected 0 argument(s), got \(args.count)")
            }
            return .int(Int())
        }

        i.registerComputed(on: "Int", name: "bitWidth") { receiver in
            let recv: Int = try unboxInt(receiver)
            return .int(recv.bitWidth)
        }

        i.registerComputed(on: "Int", name: "littleEndian") { receiver in
            let recv: Int = try unboxInt(receiver)
            return .int(recv.littleEndian)
        }

        i.registerComputed(on: "Int", name: "bigEndian") { receiver in
            let recv: Int = try unboxInt(receiver)
            return .int(recv.bigEndian)
        }

        i.registerStaticValue(on: "Int", name: "isSigned", value: .bool(Int.isSigned))

        i.registerStaticValue(on: "Int", name: "max", value: .int(Int.max))

        i.registerStaticValue(on: "Int", name: "min", value: .int(Int.min))

        i.registerMethod(on: "Int", name: "formatted") { receiver, args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("Int.formatted: expected 0 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            return .string(recv.formatted())
        }

        i.registerStaticValue(on: "String", name: "defaultCStringEncoding", value: boxOpaque(String.defaultCStringEncoding, typeName: "String.Encoding"))

        i.registerComputed(on: "String", name: "decomposedStringWithCanonicalMapping") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.decomposedStringWithCanonicalMapping)
        }

        i.registerComputed(on: "String", name: "decomposedStringWithCompatibilityMapping") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.decomposedStringWithCompatibilityMapping)
        }

        i.registerComputed(on: "String", name: "fastestEncoding") { receiver in
            let recv: String = try unboxString(receiver)
            return boxOpaque(recv.fastestEncoding, typeName: "String.Encoding")
        }

        i.registerComputed(on: "String", name: "hash") { receiver in
            let recv: String = try unboxString(receiver)
            return .int(recv.hash)
        }

        i.registerComputed(on: "String", name: "precomposedStringWithCanonicalMapping") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.precomposedStringWithCanonicalMapping)
        }

        i.registerComputed(on: "String", name: "precomposedStringWithCompatibilityMapping") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.precomposedStringWithCompatibilityMapping)
        }

        i.registerMethod(on: "String", name: "propertyList") { receiver, args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("String.propertyList: expected 0 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            _ = recv.propertyList()
            return .void
        }

        i.registerComputed(on: "String", name: "smallestEncoding") { receiver in
            let recv: String = try unboxString(receiver)
            return boxOpaque(recv.smallestEncoding, typeName: "String.Encoding")
        }

        i.registerComputed(on: "String", name: "removingPercentEncoding") { receiver in
            let recv: String = try unboxString(receiver)
            if let _v = recv.removingPercentEncoding {
            return .optional(.string(_v))
        }
        return .optional(nil)
        }

        i.registerInit(on: "Int", labels: ["integerLiteral"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int(integerLiteral:): expected 1 argument(s), got \(args.count)")
            }
            return .int(Int(integerLiteral: try unboxInt(args[0])))
        }

        i.registerMethod(on: "Int", name: "quotientAndRemainder") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int.quotientAndRemainder: expected 1 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            let _t = recv.quotientAndRemainder(dividingBy: try unboxInt(args[0]))
        return .tuple([.int(_t.0), .int(_t.1)])
        }

        i.registerInit(on: "Int", labels: ["littleEndian"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int(littleEndian:): expected 1 argument(s), got \(args.count)")
            }
            return .int(Int(littleEndian: try unboxInt(args[0])))
        }

        i.registerInit(on: "Int", labels: ["bigEndian"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int(bigEndian:): expected 1 argument(s), got \(args.count)")
            }
            return .int(Int(bigEndian: try unboxInt(args[0])))
        }

        i.registerInit(on: "String", labels: ["localized"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String(localized:): expected 1 argument(s), got \(args.count)")
            }
            return .string(String(localized: try unboxOpaque(args[0], as: LocalizedStringResource.self, typeName: "LocalizedStringResource")))
        }

        i.registerStaticMethod(on: "String", name: "localizedName") { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.localizedName: expected 1 argument(s), got \(args.count)")
            }
            return .string(String.localizedName(of: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding")))
        }

        i.registerMethod(on: "String", name: "canBeConverted") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.canBeConverted: expected 1 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .bool(recv.canBeConverted(to: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding")))
        }

        i.registerMethod(on: "String", name: "lengthOfBytes") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.lengthOfBytes: expected 1 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .int(recv.lengthOfBytes(using: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding")))
        }

        i.registerMethod(on: "String", name: "maximumLengthOfBytes") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.maximumLengthOfBytes: expected 1 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .int(recv.maximumLengthOfBytes(using: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding")))
        }

        i.registerMethod(on: "String", name: "addingPercentEncoding") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.addingPercentEncoding: expected 1 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            if let _v = recv.addingPercentEncoding(withAllowedCharacters: try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")) {
            return .optional(.string(_v))
        }
        return .optional(nil)
        }

        i.registerMethod(on: "String", name: "trimmingCharacters") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.trimmingCharacters: expected 1 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .string(recv.trimmingCharacters(in: try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")))
        }

        i.registerInit(on: "String", labels: ["data", "encoding"]) { args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("String(data:encoding:): expected 2 argument(s), got \(args.count)")
            }
            if let _v = String(data: try unboxOpaque(args[0], as: Data.self, typeName: "Data"), encoding: try unboxOpaque(args[1], as: String.Encoding.self, typeName: "String.Encoding")) {
            return .optional(.string(_v))
        }
        return .optional(nil)
        }

        i.registerInit(on: "String", labels: ["contentsOfFile", "encoding"]) { args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("String(contentsOfFile:encoding:): expected 2 argument(s), got \(args.count)")
            }
            do {
            return .string(try String(contentsOfFile: try unboxString(args[0]), encoding: try unboxOpaque(args[1], as: String.Encoding.self, typeName: "String.Encoding")))
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        }

        i.registerInit(on: "String", labels: ["contentsOf", "encoding"]) { args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("String(contentsOf:encoding:): expected 2 argument(s), got \(args.count)")
            }
            do {
            return .string(try String(contentsOf: try unboxOpaque(args[0], as: URL.self, typeName: "URL"), encoding: try unboxOpaque(args[1], as: String.Encoding.self, typeName: "String.Encoding")))
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        }

        i.registerMethod(on: "String", name: "data") { receiver, args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("String.data: expected 2 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            if let _v = recv.data(using: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding"), allowLossyConversion: try unboxBool(args[1])) {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
        }

        i.registerMethod(on: "String", name: "applyingTransform") { receiver, args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("String.applyingTransform: expected 2 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            if let _v = recv.applyingTransform(try unboxOpaque(args[0], as: StringTransform.self, typeName: "StringTransform"), reverse: try unboxBool(args[1])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
        }

        i.registerMethod(on: "String", name: "write") { receiver, args in
            guard args.count == 3 else {
                throw RuntimeError.invalid("String.write: expected 3 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            do {
            _ = try recv.write(to: try unboxOpaque(args[0], as: URL.self, typeName: "URL"), atomically: try unboxBool(args[1]), encoding: try unboxOpaque(args[2], as: String.Encoding.self, typeName: "String.Encoding"))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        }

        i.registerMethod(on: "String", name: "completePath") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.completePath: expected 1 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .int(recv.completePath(caseSensitive: try unboxBool(args[0])))
        }

        i.registerInit(on: "Bool", labels: []) { args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("Bool(): expected 0 argument(s), got \(args.count)")
            }
            return .bool(Bool())
        }

        i.registerStaticMethod(on: "Bool", name: "random") { args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("Bool.random: expected 0 argument(s), got \(args.count)")
            }
            return .bool(Bool.random())
        }

        i.registerComputed(on: "Bool", name: "description") { receiver in
            let recv: Bool = try unboxBool(receiver)
            return .string(recv.description)
        }

        i.registerComputed(on: "Bool", name: "hashValue") { receiver in
            let recv: Bool = try unboxBool(receiver)
            return .int(recv.hashValue)
        }

        i.registerComputed(on: "String", name: "hashValue") { receiver in
            let recv: String = try unboxString(receiver)
            return .int(recv.hashValue)
        }

        i.registerComputed(on: "String", name: "underestimatedCount") { receiver in
            let recv: String = try unboxString(receiver)
            return .int(recv.underestimatedCount)
        }

        i.registerInit(on: "String", labels: []) { args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("String(): expected 0 argument(s), got \(args.count)")
            }
            return .string(String())
        }

        i.registerComputed(on: "String", name: "debugDescription") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.debugDescription)
        }

        i.registerComputed(on: "String", name: "description") { receiver in
            let recv: String = try unboxString(receiver)
            return .string(recv.description)
        }

        i.registerComputed(on: "String", name: "startIndex") { receiver in
            let recv: String = try unboxString(receiver)
            return boxOpaque(recv.startIndex, typeName: "String.Index")
        }

        i.registerComputed(on: "String", name: "endIndex") { receiver in
            let recv: String = try unboxString(receiver)
            return boxOpaque(recv.endIndex, typeName: "String.Index")
        }

        i.registerComputed(on: "String", name: "count") { receiver in
            let recv: String = try unboxString(receiver)
            return .int(recv.count)
        }

        i.registerMethod(on: "String", name: "lowercased") { receiver, args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("String.lowercased: expected 0 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .string(recv.lowercased())
        }

        i.registerMethod(on: "String", name: "uppercased") { receiver, args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("String.uppercased: expected 0 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .string(recv.uppercased())
        }

        i.registerComputed(on: "String", name: "isContiguousUTF8") { receiver in
            let recv: String = try unboxString(receiver)
            return .bool(recv.isContiguousUTF8)
        }

        i.registerComputed(on: "String", name: "isEmpty") { receiver in
            let recv: String = try unboxString(receiver)
            return .bool(recv.isEmpty)
        }

        i.registerStaticValue(on: "Double", name: "ulpOfOne", value: .double(Double.ulpOfOne))

        i.registerComputed(on: "Double", name: "nextDown") { receiver in
            let recv: Double = try toDouble(receiver)
            return .double(recv.nextDown)
        }

        i.registerStaticValue(on: "Double", name: "radix", value: .int(Double.radix))

        i.registerStaticValue(on: "Double", name: "zero", value: .double(Double.zero))

        i.registerInit(on: "Double", labels: []) { args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("Double(): expected 0 argument(s), got \(args.count)")
            }
            return .double(Double())
        }

        i.registerComputed(on: "Double", name: "description") { receiver in
            let recv: Double = try toDouble(receiver)
            return .string(recv.description)
        }

        i.registerComputed(on: "Double", name: "debugDescription") { receiver in
            let recv: Double = try toDouble(receiver)
            return .string(recv.debugDescription)
        }

        i.registerStaticValue(on: "Double", name: "exponentBitCount", value: .int(Double.exponentBitCount))

        i.registerStaticValue(on: "Double", name: "significandBitCount", value: .int(Double.significandBitCount))

        i.registerComputed(on: "Double", name: "isCanonical") { receiver in
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isCanonical)
        }

        i.registerStaticValue(on: "Double", name: "infinity", value: .double(Double.infinity))

        i.registerStaticValue(on: "Double", name: "nan", value: .double(Double.nan))

        i.registerStaticValue(on: "Double", name: "signalingNaN", value: .double(Double.signalingNaN))

        i.registerStaticValue(on: "Double", name: "greatestFiniteMagnitude", value: .double(Double.greatestFiniteMagnitude))

        i.registerStaticValue(on: "Double", name: "pi", value: .double(Double.pi))

        i.registerComputed(on: "Double", name: "ulp") { receiver in
            let recv: Double = try toDouble(receiver)
            return .double(recv.ulp)
        }

        i.registerStaticValue(on: "Double", name: "leastNormalMagnitude", value: .double(Double.leastNormalMagnitude))

        i.registerStaticValue(on: "Double", name: "leastNonzeroMagnitude", value: .double(Double.leastNonzeroMagnitude))

        i.registerComputed(on: "Double", name: "exponent") { receiver in
            let recv: Double = try toDouble(receiver)
            return .int(recv.exponent)
        }

        i.registerComputed(on: "Double", name: "significand") { receiver in
            let recv: Double = try toDouble(receiver)
            return .double(recv.significand)
        }

        i.registerComputed(on: "Double", name: "nextUp") { receiver in
            let recv: Double = try toDouble(receiver)
            return .double(recv.nextUp)
        }

        i.registerComputed(on: "Double", name: "isNormal") { receiver in
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isNormal)
        }

        i.registerComputed(on: "Double", name: "isFinite") { receiver in
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isFinite)
        }

        i.registerComputed(on: "Double", name: "isZero") { receiver in
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isZero)
        }

        i.registerComputed(on: "Double", name: "isSubnormal") { receiver in
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isSubnormal)
        }

        i.registerComputed(on: "Double", name: "isInfinite") { receiver in
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isInfinite)
        }

        i.registerComputed(on: "Double", name: "isNaN") { receiver in
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isNaN)
        }

        i.registerComputed(on: "Double", name: "isSignalingNaN") { receiver in
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isSignalingNaN)
        }

        i.registerComputed(on: "Double", name: "binade") { receiver in
            let recv: Double = try toDouble(receiver)
            return .double(recv.binade)
        }

        i.registerComputed(on: "Double", name: "significandWidth") { receiver in
            let recv: Double = try toDouble(receiver)
            return .int(recv.significandWidth)
        }

        i.registerComputed(on: "Double", name: "hashValue") { receiver in
            let recv: Double = try toDouble(receiver)
            return .int(recv.hashValue)
        }

        i.registerComputed(on: "Double", name: "magnitude") { receiver in
            let recv: Double = try toDouble(receiver)
            return .double(recv.magnitude)
        }

        i.registerStaticValue(on: "Int", name: "bitWidth", value: .int(Int.bitWidth))

        i.registerComputed(on: "Int", name: "leadingZeroBitCount") { receiver in
            let recv: Int = try unboxInt(receiver)
            return .int(recv.leadingZeroBitCount)
        }

        i.registerComputed(on: "Int", name: "trailingZeroBitCount") { receiver in
            let recv: Int = try unboxInt(receiver)
            return .int(recv.trailingZeroBitCount)
        }

        i.registerComputed(on: "Int", name: "nonzeroBitCount") { receiver in
            let recv: Int = try unboxInt(receiver)
            return .int(recv.nonzeroBitCount)
        }

        i.registerComputed(on: "Int", name: "byteSwapped") { receiver in
            let recv: Int = try unboxInt(receiver)
            return .int(recv.byteSwapped)
        }

        i.registerMethod(on: "Int", name: "signum") { receiver, args in
            guard args.count == 0 else {
                throw RuntimeError.invalid("Int.signum: expected 0 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            return .int(recv.signum())
        }

        i.registerComputed(on: "Int", name: "hashValue") { receiver in
            let recv: Int = try unboxInt(receiver)
            return .int(recv.hashValue)
        }

        i.registerInit(on: "Bool", labels: ["booleanLiteral"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Bool(booleanLiteral:): expected 1 argument(s), got \(args.count)")
            }
            return .bool(Bool(booleanLiteral: try unboxBool(args[0])))
        }

        i.registerInit(on: "Int", labels: ["bitPattern"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int(bitPattern:): expected 1 argument(s), got \(args.count)")
            }
            return .int(Int(bitPattern: try unboxOpaque(args[0], as: ObjectIdentifier.self, typeName: "ObjectIdentifier")))
        }

        i.registerInit(on: "String", labels: ["stringLiteral"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String(stringLiteral:): expected 1 argument(s), got \(args.count)")
            }
            return .string(String(stringLiteral: try unboxString(args[0])))
        }

        i.registerMethod(on: "String", name: "index") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.index: expected 1 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return boxOpaque(recv.index(after: try unboxOpaque(args[0], as: String.Index.self, typeName: "String.Index")), typeName: "String.Index")
        }

        i.registerMethod(on: "String", name: "hasPrefix") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.hasPrefix: expected 1 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .bool(recv.hasPrefix(try unboxString(args[0])))
        }

        i.registerMethod(on: "String", name: "hasSuffix") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("String.hasSuffix: expected 1 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .bool(recv.hasSuffix(try unboxString(args[0])))
        }

        i.registerMethod(on: "Double", name: "truncatingRemainder") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double.truncatingRemainder: expected 1 argument(s), got \(args.count)")
            }
            let recv: Double = try toDouble(receiver)
            return .double(recv.truncatingRemainder(dividingBy: try toDouble(args[0])))
        }

        i.registerMethod(on: "Double", name: "remainder") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double.remainder: expected 1 argument(s), got \(args.count)")
            }
            let recv: Double = try toDouble(receiver)
            return .double(recv.remainder(dividingBy: try toDouble(args[0])))
        }

        i.registerMethod(on: "Double", name: "isTotallyOrdered") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double.isTotallyOrdered: expected 1 argument(s), got \(args.count)")
            }
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isTotallyOrdered(belowOrEqualTo: try toDouble(args[0])))
        }

        i.registerInit(on: "Double", labels: ["integerLiteral"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double(integerLiteral:): expected 1 argument(s), got \(args.count)")
            }
            return .double(Double(integerLiteral: try toDouble(args[0])))
        }

        i.registerMethod(on: "Double", name: "isEqual") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double.isEqual: expected 1 argument(s), got \(args.count)")
            }
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isEqual(to: try toDouble(args[0])))
        }

        i.registerMethod(on: "Double", name: "isLess") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double.isLess: expected 1 argument(s), got \(args.count)")
            }
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isLess(than: try toDouble(args[0])))
        }

        i.registerMethod(on: "Double", name: "isLessThanOrEqualTo") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double.isLessThanOrEqualTo: expected 1 argument(s), got \(args.count)")
            }
            let recv: Double = try toDouble(receiver)
            return .bool(recv.isLessThanOrEqualTo(try toDouble(args[0])))
        }

        i.registerInit(on: "Double", labels: ["floatLiteral"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double(floatLiteral:): expected 1 argument(s), got \(args.count)")
            }
            return .double(Double(floatLiteral: try toDouble(args[0])))
        }

        i.registerInit(on: "Double", labels: ["exactly"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double(exactly:): expected 1 argument(s), got \(args.count)")
            }
            if let _v = Double(exactly: try toDouble(args[0])) {
            return .optional(.double(_v))
        }
        return .optional(nil)
        }

        i.registerMethod(on: "Double", name: "distance") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double.distance: expected 1 argument(s), got \(args.count)")
            }
            let recv: Double = try toDouble(receiver)
            return .double(recv.distance(to: try toDouble(args[0])))
        }

        i.registerMethod(on: "Double", name: "advanced") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Double.advanced: expected 1 argument(s), got \(args.count)")
            }
            let recv: Double = try toDouble(receiver)
            return .double(recv.advanced(by: try toDouble(args[0])))
        }

        i.registerInit(on: "Int", labels: ["exactly"]) { args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int(exactly:): expected 1 argument(s), got \(args.count)")
            }
            if let _v = Int(exactly: try toDouble(args[0])) {
            return .optional(.int(_v))
        }
        return .optional(nil)
        }

        i.registerMethod(on: "Int", name: "addingReportingOverflow") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int.addingReportingOverflow: expected 1 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            let _t = recv.addingReportingOverflow(try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
        }

        i.registerMethod(on: "Int", name: "subtractingReportingOverflow") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int.subtractingReportingOverflow: expected 1 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            let _t = recv.subtractingReportingOverflow(try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
        }

        i.registerMethod(on: "Int", name: "multipliedReportingOverflow") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int.multipliedReportingOverflow: expected 1 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            let _t = recv.multipliedReportingOverflow(by: try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
        }

        i.registerMethod(on: "Int", name: "dividedReportingOverflow") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int.dividedReportingOverflow: expected 1 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            let _t = recv.dividedReportingOverflow(by: try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
        }

        i.registerMethod(on: "Int", name: "remainderReportingOverflow") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int.remainderReportingOverflow: expected 1 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            let _t = recv.remainderReportingOverflow(dividingBy: try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
        }

        i.registerMethod(on: "Int", name: "distance") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int.distance: expected 1 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            return .int(recv.distance(to: try unboxInt(args[0])))
        }

        i.registerMethod(on: "Int", name: "advanced") { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("Int.advanced: expected 1 argument(s), got \(args.count)")
            }
            let recv: Int = try unboxInt(receiver)
            return .int(recv.advanced(by: try unboxInt(args[0])))
        }

        i.registerMethod(on: "String", name: "distance") { receiver, args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("String.distance: expected 2 argument(s), got \(args.count)")
            }
            let recv: String = try unboxString(receiver)
            return .int(recv.distance(from: try unboxOpaque(args[0], as: String.Index.self, typeName: "String.Index"), to: try unboxOpaque(args[1], as: String.Index.self, typeName: "String.Index")))
        }

        i.registerInit(on: "String", labels: ["repeating", "count"]) { args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("String(repeating:count:): expected 2 argument(s), got \(args.count)")
            }
            return .string(String(repeating: try unboxString(args[0]), count: try unboxInt(args[1])))
        }

        i.registerMethod(on: "Double", name: "addingProduct") { receiver, args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("Double.addingProduct: expected 2 argument(s), got \(args.count)")
            }
            let recv: Double = try toDouble(receiver)
            return .double(recv.addingProduct(try toDouble(args[0]), try toDouble(args[1])))
        }

        i.registerStaticMethod(on: "Double", name: "minimum") { args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("Double.minimum: expected 2 argument(s), got \(args.count)")
            }
            return .double(Double.minimum(try toDouble(args[0]), try toDouble(args[1])))
        }

        i.registerStaticMethod(on: "Double", name: "maximum") { args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("Double.maximum: expected 2 argument(s), got \(args.count)")
            }
            return .double(Double.maximum(try toDouble(args[0]), try toDouble(args[1])))
        }

        i.registerStaticMethod(on: "Double", name: "minimumMagnitude") { args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("Double.minimumMagnitude: expected 2 argument(s), got \(args.count)")
            }
            return .double(Double.minimumMagnitude(try toDouble(args[0]), try toDouble(args[1])))
        }

        i.registerStaticMethod(on: "Double", name: "maximumMagnitude") { args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("Double.maximumMagnitude: expected 2 argument(s), got \(args.count)")
            }
            return .double(Double.maximumMagnitude(try toDouble(args[0]), try toDouble(args[1])))
        }

        i.registerInit(on: "Double", labels: ["signOf", "magnitudeOf"]) { args in
            guard args.count == 2 else {
                throw RuntimeError.invalid("Double(signOf:magnitudeOf:): expected 2 argument(s), got \(args.count)")
            }
            return .double(Double(signOf: try toDouble(args[0]), magnitudeOf: try toDouble(args[1])))
        }

        i.registerComparator(on: "OpaquePointer") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? OpaquePointer,
              case .opaque(_, let b) = rhs, let lb = b as? OpaquePointer
        else { throw RuntimeError.invalid("OpaquePointer comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "SuspendingClock.Instant") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? SuspendingClock.Instant,
              case .opaque(_, let b) = rhs, let lb = b as? SuspendingClock.Instant
        else { throw RuntimeError.invalid("SuspendingClock.Instant comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "UnsafeCurrentTask") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? UnsafeCurrentTask,
              case .opaque(_, let b) = rhs, let lb = b as? UnsafeCurrentTask
        else { throw RuntimeError.invalid("UnsafeCurrentTask comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "UnsafeRawPointer") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? UnsafeRawPointer,
              case .opaque(_, let b) = rhs, let lb = b as? UnsafeRawPointer
        else { throw RuntimeError.invalid("UnsafeRawPointer comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "String.Index") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? String.Index,
              case .opaque(_, let b) = rhs, let lb = b as? String.Index
        else { throw RuntimeError.invalid("String.Index comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "Unicode.CanonicalCombiningClass") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? Unicode.CanonicalCombiningClass,
              case .opaque(_, let b) = rhs, let lb = b as? Unicode.CanonicalCombiningClass
        else { throw RuntimeError.invalid("Unicode.CanonicalCombiningClass comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "NotificationCenter.Publisher") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? NotificationCenter.Publisher,
              case .opaque(_, let b) = rhs, let lb = b as? NotificationCenter.Publisher
        else { throw RuntimeError.invalid("NotificationCenter.Publisher comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "String.LocalizationValue") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? String.LocalizationValue,
              case .opaque(_, let b) = rhs, let lb = b as? String.LocalizationValue
        else { throw RuntimeError.invalid("String.LocalizationValue comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "TaskPriority") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? TaskPriority,
              case .opaque(_, let b) = rhs, let lb = b as? TaskPriority
        else { throw RuntimeError.invalid("TaskPriority comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "OperationQueue.SchedulerTimeType") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? OperationQueue.SchedulerTimeType,
              case .opaque(_, let b) = rhs, let lb = b as? OperationQueue.SchedulerTimeType
        else { throw RuntimeError.invalid("OperationQueue.SchedulerTimeType comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "JobPriority") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? JobPriority,
              case .opaque(_, let b) = rhs, let lb = b as? JobPriority
        else { throw RuntimeError.invalid("JobPriority comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "RegexWordBoundaryKind") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? RegexWordBoundaryKind,
              case .opaque(_, let b) = rhs, let lb = b as? RegexWordBoundaryKind
        else { throw RuntimeError.invalid("RegexWordBoundaryKind comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "RegexRepetitionBehavior") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? RegexRepetitionBehavior,
              case .opaque(_, let b) = rhs, let lb = b as? RegexRepetitionBehavior
        else { throw RuntimeError.invalid("RegexRepetitionBehavior comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "ContinuousClock.Instant") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? ContinuousClock.Instant,
              case .opaque(_, let b) = rhs, let lb = b as? ContinuousClock.Instant
        else { throw RuntimeError.invalid("ContinuousClock.Instant comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "UnownedTaskExecutor") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? UnownedTaskExecutor,
              case .opaque(_, let b) = rhs, let lb = b as? UnownedTaskExecutor
        else { throw RuntimeError.invalid("UnownedTaskExecutor comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "AnyIndex") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? AnyIndex,
              case .opaque(_, let b) = rhs, let lb = b as? AnyIndex
        else { throw RuntimeError.invalid("AnyIndex comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "Duration") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? Duration,
              case .opaque(_, let b) = rhs, let lb = b as? Duration
        else { throw RuntimeError.invalid("Duration comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "RunLoop.SchedulerTimeType") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? RunLoop.SchedulerTimeType,
              case .opaque(_, let b) = rhs, let lb = b as? RunLoop.SchedulerTimeType
        else { throw RuntimeError.invalid("RunLoop.SchedulerTimeType comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "RegexSemanticLevel") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? RegexSemanticLevel,
              case .opaque(_, let b) = rhs, let lb = b as? RegexSemanticLevel
        else { throw RuntimeError.invalid("RegexSemanticLevel comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "NotificationCenter.ObservationToken") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? NotificationCenter.ObservationToken,
              case .opaque(_, let b) = rhs, let lb = b as? NotificationCenter.ObservationToken
        else { throw RuntimeError.invalid("NotificationCenter.ObservationToken comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "String.StandardComparator") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? String.StandardComparator,
              case .opaque(_, let b) = rhs, let lb = b as? String.StandardComparator
        else { throw RuntimeError.invalid("String.StandardComparator comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "CodingUserInfoKey") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? CodingUserInfoKey,
              case .opaque(_, let b) = rhs, let lb = b as? CodingUserInfoKey
        else { throw RuntimeError.invalid("CodingUserInfoKey comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "ObjectIdentifier") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? ObjectIdentifier,
              case .opaque(_, let b) = rhs, let lb = b as? ObjectIdentifier
        else { throw RuntimeError.invalid("ObjectIdentifier comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "Duration.TimeFormatStyle") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? Duration.TimeFormatStyle,
              case .opaque(_, let b) = rhs, let lb = b as? Duration.TimeFormatStyle
        else { throw RuntimeError.invalid("Duration.TimeFormatStyle comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "String.Comparator") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? String.Comparator,
              case .opaque(_, let b) = rhs, let lb = b as? String.Comparator
        else { throw RuntimeError.invalid("String.Comparator comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "UnsafeMutableRawPointer") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? UnsafeMutableRawPointer,
              case .opaque(_, let b) = rhs, let lb = b as? UnsafeMutableRawPointer
        else { throw RuntimeError.invalid("UnsafeMutableRawPointer comparison: bad payloads") }
        return la < lb ? -1 : (la > lb ? 1 : 0)
        }

        i.registerComparator(on: "String.Encoding") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? String.Encoding,
              case .opaque(_, let b) = rhs, let lb = b as? String.Encoding
        else { throw RuntimeError.invalid("String.Encoding comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "Duration.UnitsFormatStyle") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? Duration.UnitsFormatStyle,
              case .opaque(_, let b) = rhs, let lb = b as? Duration.UnitsFormatStyle
        else { throw RuntimeError.invalid("Duration.UnitsFormatStyle comparison: bad payloads") }
        return la == lb ? 0 : -1
        }

        i.registerComparator(on: "Decimal.FormatStyle") { lhs, rhs in
            guard case .opaque(_, let a) = lhs, let la = a as? Decimal.FormatStyle,
              case .opaque(_, let b) = rhs, let lb = b as? Decimal.FormatStyle
        else { throw RuntimeError.invalid("Decimal.FormatStyle comparison: bad payloads") }
        return la == lb ? 0 : -1
        }
    }
}
