// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension StdlibBridges {
    static let int: [String: Bridge] = [
    "static let Int.zero": .staticValue(.int(Int.zero)),
    "var Int.description": .computed { receiver in
        let recv: Int = try unboxInt(receiver)
        return .string(recv.description)
    },
    "init Int()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init Int(): expected 0 argument(s), got \(args.count)")
        }
        return .int(Int())
    },
    "var Int.bitWidth": .computed { receiver in
        let recv: Int = try unboxInt(receiver)
        return .int(recv.bitWidth)
    },
    "var Int.littleEndian": .computed { receiver in
        let recv: Int = try unboxInt(receiver)
        return .int(recv.littleEndian)
    },
    "var Int.bigEndian": .computed { receiver in
        let recv: Int = try unboxInt(receiver)
        return .int(recv.bigEndian)
    },
    "static let Int.isSigned": .staticValue(.bool(Int.isSigned)),
    "static let Int.max": .staticValue(.int(Int.max)),
    "static let Int.min": .staticValue(.int(Int.min)),
    "func Int.formatted()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Int.formatted: expected 0 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        return .string(recv.formatted())
    },
    "init Int(integerLiteral:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Int(integerLiteral:): expected 1 argument(s), got \(args.count)")
        }
        return .int(Int(integerLiteral: try unboxInt(args[0])))
    },
    "func Int.quotientAndRemainder()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Int.quotientAndRemainder: expected 1 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        let _t = recv.quotientAndRemainder(dividingBy: try unboxInt(args[0]))
        return .tuple([.int(_t.0), .int(_t.1)])
    },
    "init Int(littleEndian:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Int(littleEndian:): expected 1 argument(s), got \(args.count)")
        }
        return .int(Int(littleEndian: try unboxInt(args[0])))
    },
    "init Int(bigEndian:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Int(bigEndian:): expected 1 argument(s), got \(args.count)")
        }
        return .int(Int(bigEndian: try unboxInt(args[0])))
    },
    "static let Int.bitWidth": .staticValue(.int(Int.bitWidth)),
    "var Int.leadingZeroBitCount": .computed { receiver in
        let recv: Int = try unboxInt(receiver)
        return .int(recv.leadingZeroBitCount)
    },
    "var Int.trailingZeroBitCount": .computed { receiver in
        let recv: Int = try unboxInt(receiver)
        return .int(recv.trailingZeroBitCount)
    },
    "var Int.nonzeroBitCount": .computed { receiver in
        let recv: Int = try unboxInt(receiver)
        return .int(recv.nonzeroBitCount)
    },
    "var Int.byteSwapped": .computed { receiver in
        let recv: Int = try unboxInt(receiver)
        return .int(recv.byteSwapped)
    },
    "func Int.signum()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Int.signum: expected 0 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        return .int(recv.signum())
    },
    "var Int.hashValue": .computed { receiver in
        let recv: Int = try unboxInt(receiver)
        return .int(recv.hashValue)
    },
    "init Int(bitPattern:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Int(bitPattern:): expected 1 argument(s), got \(args.count)")
        }
        return .int(Int(bitPattern: try unboxOpaque(args[0], as: ObjectIdentifier.self, typeName: "ObjectIdentifier")))
    },
    "init Int(exactly:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Int(exactly:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = Int(exactly: try toDouble(args[0])) {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "func Int.addingReportingOverflow()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Int.addingReportingOverflow: expected 1 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        let _t = recv.addingReportingOverflow(try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
    },
    "func Int.subtractingReportingOverflow()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Int.subtractingReportingOverflow: expected 1 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        let _t = recv.subtractingReportingOverflow(try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
    },
    "func Int.multipliedReportingOverflow()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Int.multipliedReportingOverflow: expected 1 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        let _t = recv.multipliedReportingOverflow(by: try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
    },
    "func Int.dividedReportingOverflow()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Int.dividedReportingOverflow: expected 1 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        let _t = recv.dividedReportingOverflow(by: try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
    },
    "func Int.remainderReportingOverflow()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Int.remainderReportingOverflow: expected 1 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        let _t = recv.remainderReportingOverflow(dividingBy: try unboxInt(args[0]))
        return .tuple([.int(_t.0), .bool(_t.1)])
    },
    "func Int.distance()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Int.distance: expected 1 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        return .int(recv.distance(to: try unboxInt(args[0])))
    },
    "func Int.advanced()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Int.advanced: expected 1 argument(s), got \(args.count)")
        }
        let recv: Int = try unboxInt(receiver)
        return .int(recv.advanced(by: try unboxInt(args[0])))
    },
    ]
}
