// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let termOfAddress: [String: Bridge] = [
    "var TermOfAddress.language": .computed { receiver in
        let recv: TermOfAddress = try unboxOpaque(receiver, as: TermOfAddress.self, typeName: "TermOfAddress")
        if let _v = recv.language {
            return .optional(boxOpaque(_v, typeName: "Locale.Language"))
        }
        return .optional(nil)
    },
    "static let TermOfAddress.neutral": .staticValue(boxOpaque(TermOfAddress.neutral, typeName: "TermOfAddress")),
    "static let TermOfAddress.feminine": .staticValue(boxOpaque(TermOfAddress.feminine, typeName: "TermOfAddress")),
    "static let TermOfAddress.masculine": .staticValue(boxOpaque(TermOfAddress.masculine, typeName: "TermOfAddress")),
    "static let TermOfAddress.currentUser": .staticValue(boxOpaque(TermOfAddress.currentUser, typeName: "TermOfAddress")),
    "var TermOfAddress.hashValue": .computed { receiver in
        let recv: TermOfAddress = try unboxOpaque(receiver, as: TermOfAddress.self, typeName: "TermOfAddress")
        return .int(recv.hashValue)
    },
    ]
}
