// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSFileVersionReplacingOptions: [String: Bridge] = [
    "init NSFileVersion.ReplacingOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSFileVersion.ReplacingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSFileVersion.ReplacingOptions(), typeName: "NSFileVersion.ReplacingOptions")
    },
    "var NSFileVersion.ReplacingOptions.isEmpty": .computed { receiver in
        let recv: NSFileVersion.ReplacingOptions = try unboxOpaque(receiver, as: NSFileVersion.ReplacingOptions.self, typeName: "NSFileVersion.ReplacingOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSFileVersion.ReplacingOptions.byMoving": .staticValue(boxOpaque(NSFileVersion.ReplacingOptions.byMoving, typeName: "NSFileVersion.ReplacingOptions")),
    ]
}
