// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let attributedStringRuns: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["var AttributedString.Runs.isEmpty: Bool"] = .computed { receiver in
        let recv: AttributedString.Runs = try unboxOpaque(receiver, as: AttributedString.Runs.self, typeName: "AttributedString.Runs")
        return .bool(recv.isEmpty)
    }
    d["var AttributedString.Runs.underestimatedCount: Int"] = .computed { receiver in
        let recv: AttributedString.Runs = try unboxOpaque(receiver, as: AttributedString.Runs.self, typeName: "AttributedString.Runs")
        return .int(recv.underestimatedCount)
    }
    d["var AttributedString.Runs.count: Int"] = .computed { receiver in
        let recv: AttributedString.Runs = try unboxOpaque(receiver, as: AttributedString.Runs.self, typeName: "AttributedString.Runs")
        return .int(recv.count)
    }
    d["var AttributedString.Runs.description: String"] = .computed { receiver in
        let recv: AttributedString.Runs = try unboxOpaque(receiver, as: AttributedString.Runs.self, typeName: "AttributedString.Runs")
        return .string(recv.description)
    }
        #endif
        return d
    }()
}
