// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let regexSemanticLevel: [String: Bridge] = [
    "static let RegexSemanticLevel.graphemeCluster": .staticValue(boxOpaque(RegexSemanticLevel.graphemeCluster, typeName: "RegexSemanticLevel")),
    "static let RegexSemanticLevel.unicodeScalar": .staticValue(boxOpaque(RegexSemanticLevel.unicodeScalar, typeName: "RegexSemanticLevel")),
    "var RegexSemanticLevel.hashValue": .computed { receiver in
        let recv: RegexSemanticLevel = try unboxOpaque(receiver, as: RegexSemanticLevel.self, typeName: "RegexSemanticLevel")
        return .int(recv.hashValue)
    },
    ]
}
