// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let byteCountFormatStyleUnits: [String: Bridge] = [
    "init ByteCountFormatStyle.Units()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init ByteCountFormatStyle.Units(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(ByteCountFormatStyle.Units(), typeName: "ByteCountFormatStyle.Units")
    },
    "var ByteCountFormatStyle.Units.hashValue": .computed { receiver in
        let recv: ByteCountFormatStyle.Units = try unboxOpaque(receiver, as: ByteCountFormatStyle.Units.self, typeName: "ByteCountFormatStyle.Units")
        return .int(recv.hashValue)
    },
    "var ByteCountFormatStyle.Units.isEmpty": .computed { receiver in
        let recv: ByteCountFormatStyle.Units = try unboxOpaque(receiver, as: ByteCountFormatStyle.Units.self, typeName: "ByteCountFormatStyle.Units")
        return .bool(recv.isEmpty)
    },
    "static let ByteCountFormatStyle.Units.bytes": .staticValue(boxOpaque(ByteCountFormatStyle.Units.bytes, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.kb": .staticValue(boxOpaque(ByteCountFormatStyle.Units.kb, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.mb": .staticValue(boxOpaque(ByteCountFormatStyle.Units.mb, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.gb": .staticValue(boxOpaque(ByteCountFormatStyle.Units.gb, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.tb": .staticValue(boxOpaque(ByteCountFormatStyle.Units.tb, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.pb": .staticValue(boxOpaque(ByteCountFormatStyle.Units.pb, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.eb": .staticValue(boxOpaque(ByteCountFormatStyle.Units.eb, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.zb": .staticValue(boxOpaque(ByteCountFormatStyle.Units.zb, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.ybOrHigher": .staticValue(boxOpaque(ByteCountFormatStyle.Units.ybOrHigher, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.all": .staticValue(boxOpaque(ByteCountFormatStyle.Units.all, typeName: "ByteCountFormatStyle.Units")),
    "static let ByteCountFormatStyle.Units.default": .staticValue(boxOpaque(ByteCountFormatStyle.Units.default, typeName: "ByteCountFormatStyle.Units")),
    ]
}
