// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let attributeContainer: [String: Bridge] = [
    "init AttributeContainer()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init AttributeContainer(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(AttributeContainer(), typeName: "AttributeContainer")
    },
    "var AttributeContainer.hashValue": .computed { receiver in
        let recv: AttributeContainer = try unboxOpaque(receiver, as: AttributeContainer.self, typeName: "AttributeContainer")
        return .int(recv.hashValue)
    },
    "var AttributeContainer.description": .computed { receiver in
        let recv: AttributeContainer = try unboxOpaque(receiver, as: AttributeContainer.self, typeName: "AttributeContainer")
        return .string(recv.description)
    },
    "func AttributeContainer.filter()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AttributeContainer.filter: expected 1 argument(s), got \(args.count)")
        }
        let recv: AttributeContainer = try unboxOpaque(receiver, as: AttributeContainer.self, typeName: "AttributeContainer")
        return boxOpaque(recv.filter(inheritedByAddedText: try unboxBool(args[0])), typeName: "AttributeContainer")
    },
    "func AttributeContainer.merging()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AttributeContainer.merging: expected 1 argument(s), got \(args.count)")
        }
        let recv: AttributeContainer = try unboxOpaque(receiver, as: AttributeContainer.self, typeName: "AttributeContainer")
        return boxOpaque(recv.merging(try unboxOpaque(args[0], as: AttributeContainer.self, typeName: "AttributeContainer")), typeName: "AttributeContainer")
    },
    ]
}
