// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSMachPortOptions: [String: Bridge] = [
    "init NSMachPort.Options()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSMachPort.Options(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSMachPort.Options(), typeName: "NSMachPort.Options")
    },
    "var NSMachPort.Options.isEmpty": .computed { receiver in
        let recv: NSMachPort.Options = try unboxOpaque(receiver, as: NSMachPort.Options.self, typeName: "NSMachPort.Options")
        return .bool(recv.isEmpty)
    },
    "static let NSMachPort.Options.deallocateSendRight": .staticValue(boxOpaque(NSMachPort.Options.deallocateSendRight, typeName: "NSMachPort.Options")),
    "static let NSMachPort.Options.deallocateReceiveRight": .staticValue(boxOpaque(NSMachPort.Options.deallocateReceiveRight, typeName: "NSMachPort.Options")),
    ]
}
