// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let measurementFormatterUnitOptions: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init MeasurementFormatter.UnitOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init MeasurementFormatter.UnitOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(MeasurementFormatter.UnitOptions(), typeName: "MeasurementFormatter.UnitOptions")
    },
    "static let MeasurementFormatter.UnitOptions.providedUnit": .staticValue(boxOpaque(MeasurementFormatter.UnitOptions.providedUnit, typeName: "MeasurementFormatter.UnitOptions")),
    "static let MeasurementFormatter.UnitOptions.naturalScale": .staticValue(boxOpaque(MeasurementFormatter.UnitOptions.naturalScale, typeName: "MeasurementFormatter.UnitOptions")),
    "static let MeasurementFormatter.UnitOptions.temperatureWithoutUnit": .staticValue(boxOpaque(MeasurementFormatter.UnitOptions.temperatureWithoutUnit, typeName: "MeasurementFormatter.UnitOptions")),
        "init MeasurementFormatter.UnitOptions(arrayLiteral:)": .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("MeasurementFormatter.UnitOptions(arrayLiteral:): expected array literal")
            }
            var result = MeasurementFormatter.UnitOptions()
            for element in elements {
                let item: MeasurementFormatter.UnitOptions = try unboxOpaque(
                    element, as: MeasurementFormatter.UnitOptions.self, typeName: "MeasurementFormatter.UnitOptions"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "MeasurementFormatter.UnitOptions")
        },
        ]
        #if canImport(Darwin)
    d["var MeasurementFormatter.UnitOptions.isEmpty: Bool"] = .computed { receiver in
        let recv: MeasurementFormatter.UnitOptions = try unboxOpaque(receiver, as: MeasurementFormatter.UnitOptions.self, typeName: "MeasurementFormatter.UnitOptions")
        return .bool(recv.isEmpty)
    }
        #endif
        return d
    }()
}
