// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let durationTimeFormatStyle: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var Duration.TimeFormatStyle.locale: Locale": .computed { receiver in
        let recv: Duration.TimeFormatStyle = try unboxOpaque(receiver, as: Duration.TimeFormatStyle.self, typeName: "Duration.TimeFormatStyle")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "var Duration.TimeFormatStyle.grouping: NumberFormatStyleConfiguration.Grouping": .computed { receiver in
        let recv: Duration.TimeFormatStyle = try unboxOpaque(receiver, as: Duration.TimeFormatStyle.self, typeName: "Duration.TimeFormatStyle")
        return boxOpaque(recv.grouping, typeName: "NumberFormatStyleConfiguration.Grouping")
    },
    "func Duration.TimeFormatStyle.format()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Duration.TimeFormatStyle.format: expected 1 argument(s), got \(args.count)")
        }
        let recv: Duration.TimeFormatStyle = try unboxOpaque(receiver, as: Duration.TimeFormatStyle.self, typeName: "Duration.TimeFormatStyle")
        return .string(recv.format(try unboxOpaque(args[0], as: Duration.self, typeName: "Duration")))
    },
    "func Duration.TimeFormatStyle.locale()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Duration.TimeFormatStyle.locale: expected 1 argument(s), got \(args.count)")
        }
        let recv: Duration.TimeFormatStyle = try unboxOpaque(receiver, as: Duration.TimeFormatStyle.self, typeName: "Duration.TimeFormatStyle")
        return boxOpaque(recv.locale(try unboxOpaque(args[0], as: Locale.self, typeName: "Locale")), typeName: "Duration.TimeFormatStyle")
    },
    "func Duration.TimeFormatStyle.grouping()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Duration.TimeFormatStyle.grouping: expected 1 argument(s), got \(args.count)")
        }
        let recv: Duration.TimeFormatStyle = try unboxOpaque(receiver, as: Duration.TimeFormatStyle.self, typeName: "Duration.TimeFormatStyle")
        return boxOpaque(recv.grouping(try unboxOpaque(args[0], as: NumberFormatStyleConfiguration.Grouping.self, typeName: "NumberFormatStyleConfiguration.Grouping")), typeName: "Duration.TimeFormatStyle")
    },
    "func Duration.TimeFormatStyle.discreteInput()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Duration.TimeFormatStyle.discreteInput: expected 1 argument(s), got \(args.count)")
        }
        let recv: Duration.TimeFormatStyle = try unboxOpaque(receiver, as: Duration.TimeFormatStyle.self, typeName: "Duration.TimeFormatStyle")
        if let _v = recv.discreteInput(before: try unboxOpaque(args[0], as: Duration.self, typeName: "Duration")) {
            return .optional(boxOpaque(_v, typeName: "Duration"))
        }
        return .optional(nil)
    },
        ]
        #if canImport(Darwin)
    d["var Duration.TimeFormatStyle.hashValue: Int"] = .computed { receiver in
        let recv: Duration.TimeFormatStyle = try unboxOpaque(receiver, as: Duration.TimeFormatStyle.self, typeName: "Duration.TimeFormatStyle")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
