// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let regexWordBoundaryKind: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["static let RegexWordBoundaryKind.simple"] = .staticValue(boxOpaque(RegexWordBoundaryKind.simple, typeName: "RegexWordBoundaryKind"))
    d["static let RegexWordBoundaryKind.default"] = .staticValue(boxOpaque(RegexWordBoundaryKind.default, typeName: "RegexWordBoundaryKind"))
    d["var RegexWordBoundaryKind.hashValue: Int"] = .computed { receiver in
        let recv: RegexWordBoundaryKind = try unboxOpaque(receiver, as: RegexWordBoundaryKind.self, typeName: "RegexWordBoundaryKind")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
