#if canImport(Darwin)
// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let descriptiveNumberFormatConfigurationPresentation: [String: Bridge] = [
    "static let DescriptiveNumberFormatConfiguration.Presentation.spellOut": .staticValue(boxOpaque(DescriptiveNumberFormatConfiguration.Presentation.spellOut, typeName: "DescriptiveNumberFormatConfiguration.Presentation")),
    "static let DescriptiveNumberFormatConfiguration.Presentation.ordinal": .staticValue(boxOpaque(DescriptiveNumberFormatConfiguration.Presentation.ordinal, typeName: "DescriptiveNumberFormatConfiguration.Presentation")),
    "var DescriptiveNumberFormatConfiguration.Presentation.hashValue: Int": .computed { receiver in
        let recv: DescriptiveNumberFormatConfiguration.Presentation = try unboxOpaque(receiver, as: DescriptiveNumberFormatConfiguration.Presentation.self, typeName: "DescriptiveNumberFormatConfiguration.Presentation")
        return .int(recv.hashValue)
    },
    ]
}
#endif
