// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let undoManagerUserInfoKey: [String: Bridge] = [
    "var UndoManager.UserInfoKey.hashValue": .computed { receiver in
        let recv: UndoManager.UserInfoKey = try unboxOpaque(receiver, as: UndoManager.UserInfoKey.self, typeName: "UndoManager.UserInfoKey")
        return .int(recv.hashValue)
    },
    "init UndoManager.UserInfoKey(_:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init UndoManager.UserInfoKey(_:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(UndoManager.UserInfoKey(try unboxString(args[0])), typeName: "UndoManager.UserInfoKey")
    },
    "init UndoManager.UserInfoKey(rawValue:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init UndoManager.UserInfoKey(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(UndoManager.UserInfoKey(rawValue: try unboxString(args[0])), typeName: "UndoManager.UserInfoKey")
    },
    ]
}
