// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let objectIdentifier: [String: Bridge] = [
    "var ObjectIdentifier.debugDescription": .computed { receiver in
        let recv: ObjectIdentifier = try unboxOpaque(receiver, as: ObjectIdentifier.self, typeName: "ObjectIdentifier")
        return .string(recv.debugDescription)
    },
    "var ObjectIdentifier.hashValue": .computed { receiver in
        let recv: ObjectIdentifier = try unboxOpaque(receiver, as: ObjectIdentifier.self, typeName: "ObjectIdentifier")
        return .int(recv.hashValue)
    },
    ]
}
