// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let fileAttributeType: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["var FileAttributeType.hashValue: Int"] = .computed { receiver in
        let recv: FileAttributeType = try unboxOpaque(receiver, as: FileAttributeType.self, typeName: "FileAttributeType")
        return .int(recv.hashValue)
    }
    d["static let FileAttributeType.typeDirectory"] = .staticValue(boxOpaque(FileAttributeType.typeDirectory, typeName: "FileAttributeType"))
    d["static let FileAttributeType.typeRegular"] = .staticValue(boxOpaque(FileAttributeType.typeRegular, typeName: "FileAttributeType"))
    d["static let FileAttributeType.typeSymbolicLink"] = .staticValue(boxOpaque(FileAttributeType.typeSymbolicLink, typeName: "FileAttributeType"))
    d["static let FileAttributeType.typeSocket"] = .staticValue(boxOpaque(FileAttributeType.typeSocket, typeName: "FileAttributeType"))
    d["static let FileAttributeType.typeCharacterSpecial"] = .staticValue(boxOpaque(FileAttributeType.typeCharacterSpecial, typeName: "FileAttributeType"))
    d["static let FileAttributeType.typeBlockSpecial"] = .staticValue(boxOpaque(FileAttributeType.typeBlockSpecial, typeName: "FileAttributeType"))
    d["static let FileAttributeType.typeUnknown"] = .staticValue(boxOpaque(FileAttributeType.typeUnknown, typeName: "FileAttributeType"))
    d["init FileAttributeType(rawValue:)"] = .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileAttributeType(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(FileAttributeType(rawValue: try unboxString(args[0])), typeName: "FileAttributeType")
    }
        #endif
        return d
    }()
}
