// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let numberFormatStyleConfigurationNotation: [String: Bridge] = [
    "static let NumberFormatStyleConfiguration.Notation.scientific": .staticValue(boxOpaque(NumberFormatStyleConfiguration.Notation.scientific, typeName: "NumberFormatStyleConfiguration.Notation")),
    "static let NumberFormatStyleConfiguration.Notation.automatic": .staticValue(boxOpaque(NumberFormatStyleConfiguration.Notation.automatic, typeName: "NumberFormatStyleConfiguration.Notation")),
    "static let NumberFormatStyleConfiguration.Notation.compactName": .staticValue(boxOpaque(NumberFormatStyleConfiguration.Notation.compactName, typeName: "NumberFormatStyleConfiguration.Notation")),
    "var NumberFormatStyleConfiguration.Notation.description: String": .computed { receiver in
        let recv: NumberFormatStyleConfiguration.Notation = try unboxOpaque(receiver, as: NumberFormatStyleConfiguration.Notation.self, typeName: "NumberFormatStyleConfiguration.Notation")
        return .string(recv.description)
    },
    "var NumberFormatStyleConfiguration.Notation.hashValue: Int": .computed { receiver in
        let recv: NumberFormatStyleConfiguration.Notation = try unboxOpaque(receiver, as: NumberFormatStyleConfiguration.Notation.self, typeName: "NumberFormatStyleConfiguration.Notation")
        return .int(recv.hashValue)
    },
    ]
}
