// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let processInfoActivityOptions: [String: Bridge] = [
    "init ProcessInfo.ActivityOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init ProcessInfo.ActivityOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(ProcessInfo.ActivityOptions(), typeName: "ProcessInfo.ActivityOptions")
    },
    "var ProcessInfo.ActivityOptions.isEmpty": .computed { receiver in
        let recv: ProcessInfo.ActivityOptions = try unboxOpaque(receiver, as: ProcessInfo.ActivityOptions.self, typeName: "ProcessInfo.ActivityOptions")
        return .bool(recv.isEmpty)
    },
    "static let ProcessInfo.ActivityOptions.idleDisplaySleepDisabled": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.idleDisplaySleepDisabled, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.idleSystemSleepDisabled": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.idleSystemSleepDisabled, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.suddenTerminationDisabled": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.suddenTerminationDisabled, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.automaticTerminationDisabled": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.automaticTerminationDisabled, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.animationTrackingEnabled": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.animationTrackingEnabled, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.trackingEnabled": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.trackingEnabled, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.userInitiated": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.userInitiated, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.userInitiatedAllowingIdleSystemSleep": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.userInitiatedAllowingIdleSystemSleep, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.background": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.background, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.latencyCritical": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.latencyCritical, typeName: "ProcessInfo.ActivityOptions")),
    "static let ProcessInfo.ActivityOptions.userInteractive": .staticValue(boxOpaque(ProcessInfo.ActivityOptions.userInteractive, typeName: "ProcessInfo.ActivityOptions")),
    ]
}
