// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let fileManager: [String: Bridge] = [
    "var FileManager.currentDirectoryPath: String": .computed { receiver in
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .string(recv.currentDirectoryPath)
    },
    "var FileManager.temporaryDirectory: URL": .computed { receiver in
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return boxOpaque(recv.temporaryDirectory, typeName: "URL")
    },
    "func FileManager.destinationOfSymbolicLink()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.destinationOfSymbolicLink: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            return .string(try recv.destinationOfSymbolicLink(atPath: try unboxString(args[0])))
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.removeItem()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.removeItem: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            _ = try recv.removeItem(atPath: try unboxString(args[0]))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.changeCurrentDirectoryPath()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.changeCurrentDirectoryPath: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .bool(recv.changeCurrentDirectoryPath(try unboxString(args[0])))
    },
    "func FileManager.fileExists()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.fileExists: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .bool(recv.fileExists(atPath: try unboxString(args[0])))
    },
    "func FileManager.isReadableFile()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isReadableFile: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .bool(recv.isReadableFile(atPath: try unboxString(args[0])))
    },
    "func FileManager.isWritableFile()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isWritableFile: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .bool(recv.isWritableFile(atPath: try unboxString(args[0])))
    },
    "func FileManager.isExecutableFile()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isExecutableFile: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .bool(recv.isExecutableFile(atPath: try unboxString(args[0])))
    },
    "func FileManager.isDeletableFile()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isDeletableFile: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .bool(recv.isDeletableFile(atPath: try unboxString(args[0])))
    },
    "func FileManager.displayName()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.displayName: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .string(recv.displayName(atPath: try unboxString(args[0])))
    },
    "func FileManager.contents()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.contents: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        if let _v = recv.contents(atPath: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
    },
    "func FileManager.isUbiquitousItem()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isUbiquitousItem: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .bool(recv.isUbiquitousItem(at: try unboxOpaque(args[0], as: URL.self, typeName: "URL")))
    },
    "func FileManager.startDownloadingUbiquitousItem()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.startDownloadingUbiquitousItem: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            _ = try recv.startDownloadingUbiquitousItem(at: try unboxOpaque(args[0], as: URL.self, typeName: "URL"))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.evictUbiquitousItem()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.evictUbiquitousItem: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            _ = try recv.evictUbiquitousItem(at: try unboxOpaque(args[0], as: URL.self, typeName: "URL"))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.containerURL()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.containerURL: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        if let _v = recv.containerURL(forSecurityApplicationGroupIdentifier: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "func FileManager.createSymbolicLink()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.createSymbolicLink: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            _ = try recv.createSymbolicLink(at: try unboxOpaque(args[0], as: URL.self, typeName: "URL"), withDestinationURL: try unboxOpaque(args[1], as: URL.self, typeName: "URL"))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.copyItem()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.copyItem: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            _ = try recv.copyItem(atPath: try unboxString(args[0]), toPath: try unboxString(args[1]))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.moveItem()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.moveItem: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            _ = try recv.moveItem(atPath: try unboxString(args[0]), toPath: try unboxString(args[1]))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.linkItem()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.linkItem: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            _ = try recv.linkItem(atPath: try unboxString(args[0]), toPath: try unboxString(args[1]))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.contentsEqual()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.contentsEqual: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return .bool(recv.contentsEqual(atPath: try unboxString(args[0]), andPath: try unboxString(args[1])))
    },
    "func FileManager.createDirectory()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.createDirectory: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            _ = try recv.createDirectory(at: try unboxOpaque(args[0], as: URL.self, typeName: "URL"), withIntermediateDirectories: try unboxBool(args[1]))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.setUbiquitous()": .method { receiver, args in
        guard args.count == 3 else {
            throw RuntimeError.invalid("FileManager.setUbiquitous: expected 3 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            _ = try recv.setUbiquitous(try unboxBool(args[0]), itemAt: try unboxOpaque(args[1], as: URL.self, typeName: "URL"), destinationURL: try unboxOpaque(args[2], as: URL.self, typeName: "URL"))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    ]
}
