// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let currencyFormatStyleConfigurationPresentation: [String: Bridge] = [
    "static let CurrencyFormatStyleConfiguration.Presentation.narrow": .staticValue(boxOpaque(CurrencyFormatStyleConfiguration.Presentation.narrow, typeName: "CurrencyFormatStyleConfiguration.Presentation")),
    "static let CurrencyFormatStyleConfiguration.Presentation.standard": .staticValue(boxOpaque(CurrencyFormatStyleConfiguration.Presentation.standard, typeName: "CurrencyFormatStyleConfiguration.Presentation")),
    "static let CurrencyFormatStyleConfiguration.Presentation.isoCode": .staticValue(boxOpaque(CurrencyFormatStyleConfiguration.Presentation.isoCode, typeName: "CurrencyFormatStyleConfiguration.Presentation")),
    "static let CurrencyFormatStyleConfiguration.Presentation.fullName": .staticValue(boxOpaque(CurrencyFormatStyleConfiguration.Presentation.fullName, typeName: "CurrencyFormatStyleConfiguration.Presentation")),
    "var CurrencyFormatStyleConfiguration.Presentation.hashValue: Int": .computed { receiver in
        let recv: CurrencyFormatStyleConfiguration.Presentation = try unboxOpaque(receiver, as: CurrencyFormatStyleConfiguration.Presentation.self, typeName: "CurrencyFormatStyleConfiguration.Presentation")
        return .int(recv.hashValue)
    },
    ]
}
