// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSRegularExpressionMatchingFlags: [String: Bridge] = [
    "init NSRegularExpression.MatchingFlags()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSRegularExpression.MatchingFlags(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSRegularExpression.MatchingFlags(), typeName: "NSRegularExpression.MatchingFlags")
    },
    "var NSRegularExpression.MatchingFlags.isEmpty: Bool": .computed { receiver in
        let recv: NSRegularExpression.MatchingFlags = try unboxOpaque(receiver, as: NSRegularExpression.MatchingFlags.self, typeName: "NSRegularExpression.MatchingFlags")
        return .bool(recv.isEmpty)
    },
    "static let NSRegularExpression.MatchingFlags.progress": .staticValue(boxOpaque(NSRegularExpression.MatchingFlags.progress, typeName: "NSRegularExpression.MatchingFlags")),
    "static let NSRegularExpression.MatchingFlags.completed": .staticValue(boxOpaque(NSRegularExpression.MatchingFlags.completed, typeName: "NSRegularExpression.MatchingFlags")),
    "static let NSRegularExpression.MatchingFlags.hitEnd": .staticValue(boxOpaque(NSRegularExpression.MatchingFlags.hitEnd, typeName: "NSRegularExpression.MatchingFlags")),
    "static let NSRegularExpression.MatchingFlags.requiredEnd": .staticValue(boxOpaque(NSRegularExpression.MatchingFlags.requiredEnd, typeName: "NSRegularExpression.MatchingFlags")),
    "static let NSRegularExpression.MatchingFlags.internalError": .staticValue(boxOpaque(NSRegularExpression.MatchingFlags.internalError, typeName: "NSRegularExpression.MatchingFlags")),
        "init NSRegularExpression.MatchingFlags(arrayLiteral:)": .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NSRegularExpression.MatchingFlags(arrayLiteral:): expected array literal")
            }
            var result = NSRegularExpression.MatchingFlags()
            for element in elements {
                let item: NSRegularExpression.MatchingFlags = try unboxOpaque(
                    element, as: NSRegularExpression.MatchingFlags.self, typeName: "NSRegularExpression.MatchingFlags"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NSRegularExpression.MatchingFlags")
        },
    ]
}
