// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let presentationIntent: [String: Bridge] = [
    "var PresentationIntent.count": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .int(recv.count)
    },
    "var PresentationIntent.debugDescription": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .string(recv.debugDescription)
    },
    "var PresentationIntent.isValid": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .bool(recv.isValid)
    },
    "var PresentationIntent.indentationLevel": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .int(recv.indentationLevel)
    },
    "var PresentationIntent.hashValue": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .int(recv.hashValue)
    },
    ]
}
