// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if canImport(Darwin)
extension FoundationBridges {
    nonisolated(unsafe) static let dateFormatString: [String: Bridge] = [
    "var Date.FormatString.hashValue: Int": .computed { receiver in
        let recv: Date.FormatString = try unboxOpaque(receiver, as: Date.FormatString.self, typeName: "Date.FormatString")
        return .int(recv.hashValue)
    },
    "init Date.FormatString(stringLiteral:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Date.FormatString(stringLiteral:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(Date.FormatString(stringLiteral: try unboxString(args[0])), typeName: "Date.FormatString")
    },
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let dateFormatString: [String: Bridge] = [:]
}
#endif
