// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let currencyFormatStyleConfigurationPresentation: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["static let CurrencyFormatStyleConfiguration.Presentation.narrow"] = .staticValue(boxOpaque(CurrencyFormatStyleConfiguration.Presentation.narrow, typeName: "CurrencyFormatStyleConfiguration.Presentation"))
    d["static let CurrencyFormatStyleConfiguration.Presentation.standard"] = .staticValue(boxOpaque(CurrencyFormatStyleConfiguration.Presentation.standard, typeName: "CurrencyFormatStyleConfiguration.Presentation"))
    d["static let CurrencyFormatStyleConfiguration.Presentation.isoCode"] = .staticValue(boxOpaque(CurrencyFormatStyleConfiguration.Presentation.isoCode, typeName: "CurrencyFormatStyleConfiguration.Presentation"))
    d["static let CurrencyFormatStyleConfiguration.Presentation.fullName"] = .staticValue(boxOpaque(CurrencyFormatStyleConfiguration.Presentation.fullName, typeName: "CurrencyFormatStyleConfiguration.Presentation"))
    d["var CurrencyFormatStyleConfiguration.Presentation.hashValue: Int"] = .computed { receiver in
        let recv: CurrencyFormatStyleConfiguration.Presentation = try unboxOpaque(receiver, as: CurrencyFormatStyleConfiguration.Presentation.self, typeName: "CurrencyFormatStyleConfiguration.Presentation")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
