// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let presentationIntent: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["var PresentationIntent.count: Int"] = .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .int(recv.count)
    }
    d["var PresentationIntent.debugDescription: String"] = .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .string(recv.debugDescription)
    }
    d["var PresentationIntent.isValid: Bool"] = .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .bool(recv.isValid)
    }
    d["var PresentationIntent.indentationLevel: Int"] = .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .int(recv.indentationLevel)
    }
    d["var PresentationIntent.hashValue: Int"] = .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
