// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let dateISO8601FormatStyle: [String: Bridge] = [
    "static let Date.ISO8601FormatStyle.iso8601": .staticValue(boxOpaque(Date.ISO8601FormatStyle.iso8601, typeName: "Date.ISO8601FormatStyle")),
    "var Date.ISO8601FormatStyle.includingFractionalSeconds": .computed { receiver in
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return .bool(recv.includingFractionalSeconds)
    },
    "var Date.ISO8601FormatStyle.timeZone": .computed { receiver in
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return boxOpaque(recv.timeZone, typeName: "TimeZone")
    },
    "func Date.ISO8601FormatStyle.year()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.ISO8601FormatStyle.year: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return boxOpaque(recv.year(), typeName: "Date.ISO8601FormatStyle")
    },
    "func Date.ISO8601FormatStyle.weekOfYear()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.ISO8601FormatStyle.weekOfYear: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return boxOpaque(recv.weekOfYear(), typeName: "Date.ISO8601FormatStyle")
    },
    "func Date.ISO8601FormatStyle.month()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.ISO8601FormatStyle.month: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return boxOpaque(recv.month(), typeName: "Date.ISO8601FormatStyle")
    },
    "func Date.ISO8601FormatStyle.day()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.ISO8601FormatStyle.day: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return boxOpaque(recv.day(), typeName: "Date.ISO8601FormatStyle")
    },
    "var Date.ISO8601FormatStyle.hashValue": .computed { receiver in
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return .int(recv.hashValue)
    },
    "var Date.ISO8601FormatStyle.parseStrategy": .computed { receiver in
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return boxOpaque(recv.parseStrategy, typeName: "Date.ISO8601FormatStyle")
    },
    "func Date.ISO8601FormatStyle.time()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.ISO8601FormatStyle.time: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return boxOpaque(recv.time(includingFractionalSeconds: try unboxBool(args[0])), typeName: "Date.ISO8601FormatStyle")
    },
    "func Date.ISO8601FormatStyle.format()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.ISO8601FormatStyle.format: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        return .string(recv.format(try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func Date.ISO8601FormatStyle.parse()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.ISO8601FormatStyle.parse: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.ISO8601FormatStyle = try unboxOpaque(receiver, as: Date.ISO8601FormatStyle.self, typeName: "Date.ISO8601FormatStyle")
        do {
            return boxOpaque(try recv.parse(try unboxString(args[0])), typeName: "Date")
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "init Date.ISO8601FormatStyle(timeZone:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Date.ISO8601FormatStyle(timeZone:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(Date.ISO8601FormatStyle(timeZone: try unboxOpaque(args[0], as: TimeZone.self, typeName: "TimeZone")), typeName: "Date.ISO8601FormatStyle")
    },
    "init Date.ISO8601FormatStyle(includingFractionalSeconds:timeZone:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init Date.ISO8601FormatStyle(includingFractionalSeconds:timeZone:): expected 2 argument(s), got \(args.count)")
        }
        return boxOpaque(Date.ISO8601FormatStyle(includingFractionalSeconds: try unboxBool(args[0]), timeZone: try unboxOpaque(args[1], as: TimeZone.self, typeName: "TimeZone")), typeName: "Date.ISO8601FormatStyle")
    },
    ]
}
