#if canImport(Darwin)
// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let streamSOCKSProxyVersion: [String: Bridge] = [
    "var StreamSOCKSProxyVersion.hashValue: Int": .computed { receiver in
        let recv: StreamSOCKSProxyVersion = try unboxOpaque(receiver, as: StreamSOCKSProxyVersion.self, typeName: "StreamSOCKSProxyVersion")
        return .int(recv.hashValue)
    },
    "static let StreamSOCKSProxyVersion.version4": .staticValue(boxOpaque(StreamSOCKSProxyVersion.version4, typeName: "StreamSOCKSProxyVersion")),
    "static let StreamSOCKSProxyVersion.version5": .staticValue(boxOpaque(StreamSOCKSProxyVersion.version5, typeName: "StreamSOCKSProxyVersion")),
    "init StreamSOCKSProxyVersion(rawValue:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init StreamSOCKSProxyVersion(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(StreamSOCKSProxyVersion(rawValue: try unboxString(args[0])), typeName: "StreamSOCKSProxyVersion")
    },
    ]
}
#endif
