// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let streamEvent: [String: Bridge] = [
    "init Stream.Event()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init Stream.Event(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(Stream.Event(), typeName: "Stream.Event")
    },
    "var Stream.Event.isEmpty": .computed { receiver in
        let recv: Stream.Event = try unboxOpaque(receiver, as: Stream.Event.self, typeName: "Stream.Event")
        return .bool(recv.isEmpty)
    },
    "static let Stream.Event.openCompleted": .staticValue(boxOpaque(Stream.Event.openCompleted, typeName: "Stream.Event")),
    "static let Stream.Event.hasBytesAvailable": .staticValue(boxOpaque(Stream.Event.hasBytesAvailable, typeName: "Stream.Event")),
    "static let Stream.Event.hasSpaceAvailable": .staticValue(boxOpaque(Stream.Event.hasSpaceAvailable, typeName: "Stream.Event")),
    "static let Stream.Event.errorOccurred": .staticValue(boxOpaque(Stream.Event.errorOccurred, typeName: "Stream.Event")),
    "static let Stream.Event.endEncountered": .staticValue(boxOpaque(Stream.Event.endEncountered, typeName: "Stream.Event")),
    ]
}
