// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if canImport(Darwin)
extension FoundationBridges {
    nonisolated(unsafe) static let nSFileManagerSupportedSyncControls: [String: Bridge] = [
    "init NSFileManagerSupportedSyncControls()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSFileManagerSupportedSyncControls(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSFileManagerSupportedSyncControls(), typeName: "NSFileManagerSupportedSyncControls")
    },
    "var NSFileManagerSupportedSyncControls.isEmpty: Bool": .computed { receiver in
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isEmpty)
    },
    "static let NSFileManagerSupportedSyncControls.pauseSync": .staticValue(boxOpaque(NSFileManagerSupportedSyncControls.pauseSync, typeName: "NSFileManagerSupportedSyncControls")),
    "static let NSFileManagerSupportedSyncControls.failUploadOnConflict": .staticValue(boxOpaque(NSFileManagerSupportedSyncControls.failUploadOnConflict, typeName: "NSFileManagerSupportedSyncControls")),
    "func NSFileManagerSupportedSyncControls.union()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.union: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return boxOpaque(recv.union(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")), typeName: "NSFileManagerSupportedSyncControls")
    },
    "func NSFileManagerSupportedSyncControls.intersection()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.intersection: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return boxOpaque(recv.intersection(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")), typeName: "NSFileManagerSupportedSyncControls")
    },
    "func NSFileManagerSupportedSyncControls.symmetricDifference()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.symmetricDifference: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return boxOpaque(recv.symmetricDifference(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")), typeName: "NSFileManagerSupportedSyncControls")
    },
    "func NSFileManagerSupportedSyncControls.contains()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.contains: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.contains(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    },
    "func NSFileManagerSupportedSyncControls.isSubset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isSubset(of: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    },
    "func NSFileManagerSupportedSyncControls.isSuperset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isSuperset(of: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    },
    "func NSFileManagerSupportedSyncControls.isDisjoint()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isDisjoint: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isDisjoint(with: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    },
    "func NSFileManagerSupportedSyncControls.subtracting()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.subtracting: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return boxOpaque(recv.subtracting(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")), typeName: "NSFileManagerSupportedSyncControls")
    },
    "func NSFileManagerSupportedSyncControls.isStrictSuperset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isStrictSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isStrictSuperset(of: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    },
    "func NSFileManagerSupportedSyncControls.isStrictSubset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isStrictSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isStrictSubset(of: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    },
        "init NSFileManagerSupportedSyncControls(arrayLiteral:)": .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NSFileManagerSupportedSyncControls(arrayLiteral:): expected array literal")
            }
            var result = NSFileManagerSupportedSyncControls()
            for element in elements {
                let item: NSFileManagerSupportedSyncControls = try unboxOpaque(
                    element, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NSFileManagerSupportedSyncControls")
        },
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let nSFileManagerSupportedSyncControls: [String: Bridge] = [:]
}
#endif
