// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let dateParseStrategy: [String: Bridge] = [
    "var Date.ParseStrategy.isLenient": .computed { receiver in
        let recv: Date.ParseStrategy = try unboxOpaque(receiver, as: Date.ParseStrategy.self, typeName: "Date.ParseStrategy")
        return .bool(recv.isLenient)
    },
    "var Date.ParseStrategy.twoDigitStartDate": .computed { receiver in
        let recv: Date.ParseStrategy = try unboxOpaque(receiver, as: Date.ParseStrategy.self, typeName: "Date.ParseStrategy")
        return boxOpaque(recv.twoDigitStartDate, typeName: "Date")
    },
    "var Date.ParseStrategy.locale": .computed { receiver in
        let recv: Date.ParseStrategy = try unboxOpaque(receiver, as: Date.ParseStrategy.self, typeName: "Date.ParseStrategy")
        if let _v = recv.locale {
            return .optional(boxOpaque(_v, typeName: "Locale"))
        }
        return .optional(nil)
    },
    "var Date.ParseStrategy.timeZone": .computed { receiver in
        let recv: Date.ParseStrategy = try unboxOpaque(receiver, as: Date.ParseStrategy.self, typeName: "Date.ParseStrategy")
        return boxOpaque(recv.timeZone, typeName: "TimeZone")
    },
    "var Date.ParseStrategy.calendar": .computed { receiver in
        let recv: Date.ParseStrategy = try unboxOpaque(receiver, as: Date.ParseStrategy.self, typeName: "Date.ParseStrategy")
        return boxOpaque(recv.calendar, typeName: "Calendar")
    },
    "var Date.ParseStrategy.format": .computed { receiver in
        let recv: Date.ParseStrategy = try unboxOpaque(receiver, as: Date.ParseStrategy.self, typeName: "Date.ParseStrategy")
        return .string(recv.format)
    },
    "var Date.ParseStrategy.hashValue": .computed { receiver in
        let recv: Date.ParseStrategy = try unboxOpaque(receiver, as: Date.ParseStrategy.self, typeName: "Date.ParseStrategy")
        return .int(recv.hashValue)
    },
    "func Date.ParseStrategy.parse()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.ParseStrategy.parse: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.ParseStrategy = try unboxOpaque(receiver, as: Date.ParseStrategy.self, typeName: "Date.ParseStrategy")
        do {
            return boxOpaque(try recv.parse(try unboxString(args[0])), typeName: "Date")
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    ]
}
