#if canImport(Darwin)
// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let notification: [String: Bridge] = [
    "var Notification.description: String": .computed { receiver in
        let recv: Notification = try unboxOpaque(receiver, as: Notification.self, typeName: "Notification")
        return .string(recv.description)
    },
    "var Notification.debugDescription: String": .computed { receiver in
        let recv: Notification = try unboxOpaque(receiver, as: Notification.self, typeName: "Notification")
        return .string(recv.debugDescription)
    },
    "var Notification.hashValue: Int": .computed { receiver in
        let recv: Notification = try unboxOpaque(receiver, as: Notification.self, typeName: "Notification")
        return .int(recv.hashValue)
    },
    ]
}
#endif
