// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSCalendarIdentifier: [String: Bridge] = [
    "var NSCalendar.Identifier.hashValue": .computed { receiver in
        let recv: NSCalendar.Identifier = try unboxOpaque(receiver, as: NSCalendar.Identifier.self, typeName: "NSCalendar.Identifier")
        return .int(recv.hashValue)
    },
    "static let NSCalendar.Identifier.gregorian": .staticValue(boxOpaque(NSCalendar.Identifier.gregorian, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.buddhist": .staticValue(boxOpaque(NSCalendar.Identifier.buddhist, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.chinese": .staticValue(boxOpaque(NSCalendar.Identifier.chinese, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.coptic": .staticValue(boxOpaque(NSCalendar.Identifier.coptic, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.ethiopicAmeteMihret": .staticValue(boxOpaque(NSCalendar.Identifier.ethiopicAmeteMihret, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.ethiopicAmeteAlem": .staticValue(boxOpaque(NSCalendar.Identifier.ethiopicAmeteAlem, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.hebrew": .staticValue(boxOpaque(NSCalendar.Identifier.hebrew, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.ISO8601": .staticValue(boxOpaque(NSCalendar.Identifier.ISO8601, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.indian": .staticValue(boxOpaque(NSCalendar.Identifier.indian, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.islamic": .staticValue(boxOpaque(NSCalendar.Identifier.islamic, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.islamicCivil": .staticValue(boxOpaque(NSCalendar.Identifier.islamicCivil, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.japanese": .staticValue(boxOpaque(NSCalendar.Identifier.japanese, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.persian": .staticValue(boxOpaque(NSCalendar.Identifier.persian, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.republicOfChina": .staticValue(boxOpaque(NSCalendar.Identifier.republicOfChina, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.islamicTabular": .staticValue(boxOpaque(NSCalendar.Identifier.islamicTabular, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.islamicUmmAlQura": .staticValue(boxOpaque(NSCalendar.Identifier.islamicUmmAlQura, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.bangla": .staticValue(boxOpaque(NSCalendar.Identifier.bangla, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.gujarati": .staticValue(boxOpaque(NSCalendar.Identifier.gujarati, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.kannada": .staticValue(boxOpaque(NSCalendar.Identifier.kannada, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.malayalam": .staticValue(boxOpaque(NSCalendar.Identifier.malayalam, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.marathi": .staticValue(boxOpaque(NSCalendar.Identifier.marathi, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.odia": .staticValue(boxOpaque(NSCalendar.Identifier.odia, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.tamil": .staticValue(boxOpaque(NSCalendar.Identifier.tamil, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.telugu": .staticValue(boxOpaque(NSCalendar.Identifier.telugu, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.vikram": .staticValue(boxOpaque(NSCalendar.Identifier.vikram, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.dangi": .staticValue(boxOpaque(NSCalendar.Identifier.dangi, typeName: "NSCalendar.Identifier")),
    "static let NSCalendar.Identifier.vietnamese": .staticValue(boxOpaque(NSCalendar.Identifier.vietnamese, typeName: "NSCalendar.Identifier")),
    "init NSCalendar.Identifier(_:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init NSCalendar.Identifier(_:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(NSCalendar.Identifier(try unboxString(args[0])), typeName: "NSCalendar.Identifier")
    },
    "init NSCalendar.Identifier(rawValue:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init NSCalendar.Identifier(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(NSCalendar.Identifier(rawValue: try unboxString(args[0])), typeName: "NSCalendar.Identifier")
    },
    ]
}
