// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let attributedStringInterpolationOptions: [String: Bridge] = [
    "init AttributedString.InterpolationOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init AttributedString.InterpolationOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(AttributedString.InterpolationOptions(), typeName: "AttributedString.InterpolationOptions")
    },
    "var AttributedString.InterpolationOptions.isEmpty": .computed { receiver in
        let recv: AttributedString.InterpolationOptions = try unboxOpaque(receiver, as: AttributedString.InterpolationOptions.self, typeName: "AttributedString.InterpolationOptions")
        return .bool(recv.isEmpty)
    },
    "static let AttributedString.InterpolationOptions.insertAttributesWithoutMerging": .staticValue(boxOpaque(AttributedString.InterpolationOptions.insertAttributesWithoutMerging, typeName: "AttributedString.InterpolationOptions")),
    ]
}
