// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSExceptionName: [String: Bridge] = [
    "static let NSExceptionName.fileHandleOperationException": .staticValue(boxOpaque(NSExceptionName.fileHandleOperationException, typeName: "NSExceptionName")),
    "static let NSExceptionName.invalidArchiveOperationException": .staticValue(boxOpaque(NSExceptionName.invalidArchiveOperationException, typeName: "NSExceptionName")),
    "static let NSExceptionName.invalidUnarchiveOperationException": .staticValue(boxOpaque(NSExceptionName.invalidUnarchiveOperationException, typeName: "NSExceptionName")),
    "static let NSExceptionName.decimalNumberExactnessException": .staticValue(boxOpaque(NSExceptionName.decimalNumberExactnessException, typeName: "NSExceptionName")),
    "static let NSExceptionName.decimalNumberOverflowException": .staticValue(boxOpaque(NSExceptionName.decimalNumberOverflowException, typeName: "NSExceptionName")),
    "static let NSExceptionName.decimalNumberUnderflowException": .staticValue(boxOpaque(NSExceptionName.decimalNumberUnderflowException, typeName: "NSExceptionName")),
    "static let NSExceptionName.decimalNumberDivideByZeroException": .staticValue(boxOpaque(NSExceptionName.decimalNumberDivideByZeroException, typeName: "NSExceptionName")),
    "static let NSExceptionName.genericException": .staticValue(boxOpaque(NSExceptionName.genericException, typeName: "NSExceptionName")),
    "static let NSExceptionName.rangeException": .staticValue(boxOpaque(NSExceptionName.rangeException, typeName: "NSExceptionName")),
    "static let NSExceptionName.invalidArgumentException": .staticValue(boxOpaque(NSExceptionName.invalidArgumentException, typeName: "NSExceptionName")),
    "static let NSExceptionName.internalInconsistencyException": .staticValue(boxOpaque(NSExceptionName.internalInconsistencyException, typeName: "NSExceptionName")),
    "static let NSExceptionName.mallocException": .staticValue(boxOpaque(NSExceptionName.mallocException, typeName: "NSExceptionName")),
    "static let NSExceptionName.objectInaccessibleException": .staticValue(boxOpaque(NSExceptionName.objectInaccessibleException, typeName: "NSExceptionName")),
    "static let NSExceptionName.objectNotAvailableException": .staticValue(boxOpaque(NSExceptionName.objectNotAvailableException, typeName: "NSExceptionName")),
    "static let NSExceptionName.destinationInvalidException": .staticValue(boxOpaque(NSExceptionName.destinationInvalidException, typeName: "NSExceptionName")),
    "static let NSExceptionName.portTimeoutException": .staticValue(boxOpaque(NSExceptionName.portTimeoutException, typeName: "NSExceptionName")),
    "static let NSExceptionName.invalidSendPortException": .staticValue(boxOpaque(NSExceptionName.invalidSendPortException, typeName: "NSExceptionName")),
    "static let NSExceptionName.invalidReceivePortException": .staticValue(boxOpaque(NSExceptionName.invalidReceivePortException, typeName: "NSExceptionName")),
    "static let NSExceptionName.portSendException": .staticValue(boxOpaque(NSExceptionName.portSendException, typeName: "NSExceptionName")),
    "static let NSExceptionName.portReceiveException": .staticValue(boxOpaque(NSExceptionName.portReceiveException, typeName: "NSExceptionName")),
    "static let NSExceptionName.oldStyleException": .staticValue(boxOpaque(NSExceptionName.oldStyleException, typeName: "NSExceptionName")),
    "static let NSExceptionName.inconsistentArchiveException": .staticValue(boxOpaque(NSExceptionName.inconsistentArchiveException, typeName: "NSExceptionName")),
    "static let NSExceptionName.invocationOperationVoidResultException": .staticValue(boxOpaque(NSExceptionName.invocationOperationVoidResultException, typeName: "NSExceptionName")),
    "static let NSExceptionName.invocationOperationCancelledException": .staticValue(boxOpaque(NSExceptionName.invocationOperationCancelledException, typeName: "NSExceptionName")),
    "var NSExceptionName.hashValue: Int": .computed { receiver in
        let recv: NSExceptionName = try unboxOpaque(receiver, as: NSExceptionName.self, typeName: "NSExceptionName")
        return .int(recv.hashValue)
    },
    "static let NSExceptionName.characterConversionException": .staticValue(boxOpaque(NSExceptionName.characterConversionException, typeName: "NSExceptionName")),
    "static let NSExceptionName.parseErrorException": .staticValue(boxOpaque(NSExceptionName.parseErrorException, typeName: "NSExceptionName")),
    "static let NSExceptionName.undefinedKeyException": .staticValue(boxOpaque(NSExceptionName.undefinedKeyException, typeName: "NSExceptionName")),
    "init NSExceptionName(_:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init NSExceptionName(_:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(NSExceptionName(try unboxString(args[0])), typeName: "NSExceptionName")
    },
    "init NSExceptionName(rawValue:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init NSExceptionName(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(NSExceptionName(rawValue: try unboxString(args[0])), typeName: "NSExceptionName")
    },
    ]
}
