// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let jSONEncoder: [String: Bridge] = [
        "func JSONEncoder.encode<T: Encodable>(_: T) throws -> Data": .method { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("JSONEncoder.encode: expected 1 argument(s), got \(args.count)")
            }
            let recv: JSONEncoder = try unboxOpaque(receiver, as: JSONEncoder.self, typeName: "JSONEncoder")
            do {
                return .opaque(typeName: "Data", value: try recv.encode(ScriptCodable(args[0])))
            } catch {
                throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
            }
        },
    ]
}
