// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let nSTextCheckingKey: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init NSTextCheckingKey(_:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init NSTextCheckingKey(_:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(NSTextCheckingKey(try unboxString(args[0])), typeName: "NSTextCheckingKey")
    },
        ]
        #if canImport(Darwin)
    d["var NSTextCheckingKey.hashValue: Int"] = .computed { receiver in
        let recv: NSTextCheckingKey = try unboxOpaque(receiver, as: NSTextCheckingKey.self, typeName: "NSTextCheckingKey")
        return .int(recv.hashValue)
    }
    d["static let NSTextCheckingKey.name"] = .staticValue(boxOpaque(NSTextCheckingKey.name, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.jobTitle"] = .staticValue(boxOpaque(NSTextCheckingKey.jobTitle, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.organization"] = .staticValue(boxOpaque(NSTextCheckingKey.organization, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.street"] = .staticValue(boxOpaque(NSTextCheckingKey.street, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.city"] = .staticValue(boxOpaque(NSTextCheckingKey.city, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.state"] = .staticValue(boxOpaque(NSTextCheckingKey.state, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.zip"] = .staticValue(boxOpaque(NSTextCheckingKey.zip, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.country"] = .staticValue(boxOpaque(NSTextCheckingKey.country, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.phone"] = .staticValue(boxOpaque(NSTextCheckingKey.phone, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.airline"] = .staticValue(boxOpaque(NSTextCheckingKey.airline, typeName: "NSTextCheckingKey"))
    d["static let NSTextCheckingKey.flight"] = .staticValue(boxOpaque(NSTextCheckingKey.flight, typeName: "NSTextCheckingKey"))
        #endif
        return d
    }()
}
