// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSSortOptions: [String: Bridge] = [
    "init NSSortOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSSortOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSSortOptions(), typeName: "NSSortOptions")
    },
    "var NSSortOptions.isEmpty: Bool": .computed { receiver in
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSSortOptions.concurrent": .staticValue(boxOpaque(NSSortOptions.concurrent, typeName: "NSSortOptions")),
    "static let NSSortOptions.stable": .staticValue(boxOpaque(NSSortOptions.stable, typeName: "NSSortOptions")),
    "func NSSortOptions.union()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.union: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return boxOpaque(recv.union(try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")), typeName: "NSSortOptions")
    },
    "func NSSortOptions.intersection()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.intersection: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return boxOpaque(recv.intersection(try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")), typeName: "NSSortOptions")
    },
    "func NSSortOptions.symmetricDifference()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.symmetricDifference: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return boxOpaque(recv.symmetricDifference(try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")), typeName: "NSSortOptions")
    },
    "func NSSortOptions.contains()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.contains: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return .bool(recv.contains(try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")))
    },
    "func NSSortOptions.isSubset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.isSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return .bool(recv.isSubset(of: try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")))
    },
    "func NSSortOptions.isSuperset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.isSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return .bool(recv.isSuperset(of: try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")))
    },
    "func NSSortOptions.isDisjoint()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.isDisjoint: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return .bool(recv.isDisjoint(with: try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")))
    },
    "func NSSortOptions.subtracting()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.subtracting: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return boxOpaque(recv.subtracting(try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")), typeName: "NSSortOptions")
    },
    "func NSSortOptions.isStrictSuperset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.isStrictSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return .bool(recv.isStrictSuperset(of: try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")))
    },
    "func NSSortOptions.isStrictSubset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSSortOptions.isStrictSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSSortOptions = try unboxOpaque(receiver, as: NSSortOptions.self, typeName: "NSSortOptions")
        return .bool(recv.isStrictSubset(of: try unboxOpaque(args[0], as: NSSortOptions.self, typeName: "NSSortOptions")))
    },
        "init NSSortOptions(arrayLiteral:)": .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NSSortOptions(arrayLiteral:): expected array literal")
            }
            var result = NSSortOptions()
            for element in elements {
                let item: NSSortOptions = try unboxOpaque(
                    element, as: NSSortOptions.self, typeName: "NSSortOptions"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NSSortOptions")
        },
    ]
}
