// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let presentationIntentTableColumn: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["var PresentationIntent.TableColumn.hashValue: Int"] = .computed { receiver in
        let recv: PresentationIntent.TableColumn = try unboxOpaque(receiver, as: PresentationIntent.TableColumn.self, typeName: "PresentationIntent.TableColumn")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
