// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let regexRepetitionBehavior: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["var RegexRepetitionBehavior.hashValue: Int"] = .computed { receiver in
        let recv: RegexRepetitionBehavior = try unboxOpaque(receiver, as: RegexRepetitionBehavior.self, typeName: "RegexRepetitionBehavior")
        return .int(recv.hashValue)
    }
    d["static let RegexRepetitionBehavior.eager"] = .staticValue(boxOpaque(RegexRepetitionBehavior.eager, typeName: "RegexRepetitionBehavior"))
    d["static let RegexRepetitionBehavior.reluctant"] = .staticValue(boxOpaque(RegexRepetitionBehavior.reluctant, typeName: "RegexRepetitionBehavior"))
    d["static let RegexRepetitionBehavior.possessive"] = .staticValue(boxOpaque(RegexRepetitionBehavior.possessive, typeName: "RegexRepetitionBehavior"))
        #endif
        return d
    }()
}
