#if canImport(Darwin)
// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let dateHTTPFormatStyle: [String: Bridge] = [
    "var Date.HTTPFormatStyle.parseStrategy: Date.HTTPFormatStyle": .computed { receiver in
        let recv: Date.HTTPFormatStyle = try unboxOpaque(receiver, as: Date.HTTPFormatStyle.self, typeName: "Date.HTTPFormatStyle")
        return boxOpaque(recv.parseStrategy, typeName: "Date.HTTPFormatStyle")
    },
    "init Date.HTTPFormatStyle()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init Date.HTTPFormatStyle(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(Date.HTTPFormatStyle(), typeName: "Date.HTTPFormatStyle")
    },
    "var Date.HTTPFormatStyle.hashValue: Int": .computed { receiver in
        let recv: Date.HTTPFormatStyle = try unboxOpaque(receiver, as: Date.HTTPFormatStyle.self, typeName: "Date.HTTPFormatStyle")
        return .int(recv.hashValue)
    },
    "func Date.HTTPFormatStyle.format()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.HTTPFormatStyle.format: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.HTTPFormatStyle = try unboxOpaque(receiver, as: Date.HTTPFormatStyle.self, typeName: "Date.HTTPFormatStyle")
        return .string(recv.format(try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func Date.HTTPFormatStyle.parse()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.HTTPFormatStyle.parse: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.HTTPFormatStyle = try unboxOpaque(receiver, as: Date.HTTPFormatStyle.self, typeName: "Date.HTTPFormatStyle")
        do {
            return boxOpaque(try recv.parse(try unboxString(args[0])), typeName: "Date")
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    ]
}
#endif
