// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let formatStyleCapitalizationContext: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["static let FormatStyleCapitalizationContext.unknown"] = .staticValue(boxOpaque(FormatStyleCapitalizationContext.unknown, typeName: "FormatStyleCapitalizationContext"))
    d["static let FormatStyleCapitalizationContext.standalone"] = .staticValue(boxOpaque(FormatStyleCapitalizationContext.standalone, typeName: "FormatStyleCapitalizationContext"))
    d["static let FormatStyleCapitalizationContext.listItem"] = .staticValue(boxOpaque(FormatStyleCapitalizationContext.listItem, typeName: "FormatStyleCapitalizationContext"))
    d["static let FormatStyleCapitalizationContext.beginningOfSentence"] = .staticValue(boxOpaque(FormatStyleCapitalizationContext.beginningOfSentence, typeName: "FormatStyleCapitalizationContext"))
    d["static let FormatStyleCapitalizationContext.middleOfSentence"] = .staticValue(boxOpaque(FormatStyleCapitalizationContext.middleOfSentence, typeName: "FormatStyleCapitalizationContext"))
    d["var FormatStyleCapitalizationContext.hashValue: Int"] = .computed { receiver in
        let recv: FormatStyleCapitalizationContext = try unboxOpaque(receiver, as: FormatStyleCapitalizationContext.self, typeName: "FormatStyleCapitalizationContext")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
