// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let pOSIXError: [String: Bridge] = [
    "var POSIXError.errorCode": .computed { receiver in
        let recv: POSIXError = try unboxOpaque(receiver, as: POSIXError.self, typeName: "POSIXError")
        return .int(recv.errorCode)
    },
    "static let POSIXError.errorDomain": .staticValue(.string(POSIXError.errorDomain)),
    "var POSIXError.localizedDescription": .computed { receiver in
        let recv: POSIXError = try unboxOpaque(receiver, as: POSIXError.self, typeName: "POSIXError")
        return .string(recv.localizedDescription)
    },
    "var POSIXError.hashValue": .computed { receiver in
        let recv: POSIXError = try unboxOpaque(receiver, as: POSIXError.self, typeName: "POSIXError")
        return .int(recv.hashValue)
    },
    ]
}
