// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let discontiguousAttributedSubstring: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["var DiscontiguousAttributedSubstring.base: AttributedString"] = .computed { receiver in
        let recv: DiscontiguousAttributedSubstring = try unboxOpaque(receiver, as: DiscontiguousAttributedSubstring.self, typeName: "DiscontiguousAttributedSubstring")
        return boxOpaque(recv.base, typeName: "AttributedString")
    }
    d["var DiscontiguousAttributedSubstring.description: String"] = .computed { receiver in
        let recv: DiscontiguousAttributedSubstring = try unboxOpaque(receiver, as: DiscontiguousAttributedSubstring.self, typeName: "DiscontiguousAttributedSubstring")
        return .string(recv.description)
    }
    d["var DiscontiguousAttributedSubstring.hashValue: Int"] = .computed { receiver in
        let recv: DiscontiguousAttributedSubstring = try unboxOpaque(receiver, as: DiscontiguousAttributedSubstring.self, typeName: "DiscontiguousAttributedSubstring")
        return .int(recv.hashValue)
    }
    d["var DiscontiguousAttributedSubstring.runs: AttributedString.Runs"] = .computed { receiver in
        let recv: DiscontiguousAttributedSubstring = try unboxOpaque(receiver, as: DiscontiguousAttributedSubstring.self, typeName: "DiscontiguousAttributedSubstring")
        return boxOpaque(recv.runs, typeName: "AttributedString.Runs")
    }
        #endif
        return d
    }()
}
