// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let uRLRequest: [String: Bridge] = [
    "var URLRequest.url": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.url {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "var URLRequest.timeoutInterval": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .double(recv.timeoutInterval)
    },
    "var URLRequest.mainDocumentURL": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.mainDocumentURL {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "var URLRequest.allowsCellularAccess": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.allowsCellularAccess)
    },
    "var URLRequest.allowsExpensiveNetworkAccess": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.allowsExpensiveNetworkAccess)
    },
    "var URLRequest.allowsConstrainedNetworkAccess": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.allowsConstrainedNetworkAccess)
    },
    "var URLRequest.assumesHTTP3Capable": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.assumesHTTP3Capable)
    },
    "var URLRequest.requiresDNSSECValidation": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.requiresDNSSECValidation)
    },
    "var URLRequest.allowsPersistentDNS": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.allowsPersistentDNS)
    },
    "var URLRequest.httpMethod": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.httpMethod {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLRequest.httpBody": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.httpBody {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
    },
    "var URLRequest.httpShouldHandleCookies": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.httpShouldHandleCookies)
    },
    "var URLRequest.cookiePartitionIdentifier": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.cookiePartitionIdentifier {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLRequest.hashValue": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .int(recv.hashValue)
    },
    "var URLRequest.description": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .string(recv.description)
    },
    "var URLRequest.debugDescription": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .string(recv.debugDescription)
    },
    "func URLRequest.value()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URLRequest.value: expected 1 argument(s), got \(args.count)")
        }
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.value(forHTTPHeaderField: try unboxString(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "init URLRequest(url:timeoutInterval:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init URLRequest(url:timeoutInterval:): expected 2 argument(s), got \(args.count)")
        }
        return boxOpaque(URLRequest(url: try unboxOpaque(args[0], as: URL.self, typeName: "URL"), timeoutInterval: try toDouble(args[1])), typeName: "URLRequest")
    },
    ]
}
