// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSStringEnumerationOptions: [String: Bridge] = [
    "init NSString.EnumerationOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSString.EnumerationOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSString.EnumerationOptions(), typeName: "NSString.EnumerationOptions")
    },
    "var NSString.EnumerationOptions.isEmpty": .computed { receiver in
        let recv: NSString.EnumerationOptions = try unboxOpaque(receiver, as: NSString.EnumerationOptions.self, typeName: "NSString.EnumerationOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSString.EnumerationOptions.byLines": .staticValue(boxOpaque(NSString.EnumerationOptions.byLines, typeName: "NSString.EnumerationOptions")),
    "static let NSString.EnumerationOptions.byParagraphs": .staticValue(boxOpaque(NSString.EnumerationOptions.byParagraphs, typeName: "NSString.EnumerationOptions")),
    "static let NSString.EnumerationOptions.byComposedCharacterSequences": .staticValue(boxOpaque(NSString.EnumerationOptions.byComposedCharacterSequences, typeName: "NSString.EnumerationOptions")),
    "static let NSString.EnumerationOptions.byWords": .staticValue(boxOpaque(NSString.EnumerationOptions.byWords, typeName: "NSString.EnumerationOptions")),
    "static let NSString.EnumerationOptions.bySentences": .staticValue(boxOpaque(NSString.EnumerationOptions.bySentences, typeName: "NSString.EnumerationOptions")),
    "static let NSString.EnumerationOptions.byCaretPositions": .staticValue(boxOpaque(NSString.EnumerationOptions.byCaretPositions, typeName: "NSString.EnumerationOptions")),
    "static let NSString.EnumerationOptions.byDeletionClusters": .staticValue(boxOpaque(NSString.EnumerationOptions.byDeletionClusters, typeName: "NSString.EnumerationOptions")),
    "static let NSString.EnumerationOptions.reverse": .staticValue(boxOpaque(NSString.EnumerationOptions.reverse, typeName: "NSString.EnumerationOptions")),
    "static let NSString.EnumerationOptions.substringNotRequired": .staticValue(boxOpaque(NSString.EnumerationOptions.substringNotRequired, typeName: "NSString.EnumerationOptions")),
    "static let NSString.EnumerationOptions.localized": .staticValue(boxOpaque(NSString.EnumerationOptions.localized, typeName: "NSString.EnumerationOptions")),
    ]
}
