// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let taskPriority: [String: Bridge] = [
    "static let TaskPriority.high": .staticValue(boxOpaque(TaskPriority.high, typeName: "TaskPriority")),
    "static let TaskPriority.medium": .staticValue(boxOpaque(TaskPriority.medium, typeName: "TaskPriority")),
    "static let TaskPriority.low": .staticValue(boxOpaque(TaskPriority.low, typeName: "TaskPriority")),
    "static let TaskPriority.userInitiated": .staticValue(boxOpaque(TaskPriority.userInitiated, typeName: "TaskPriority")),
    "static let TaskPriority.utility": .staticValue(boxOpaque(TaskPriority.utility, typeName: "TaskPriority")),
    "static let TaskPriority.background": .staticValue(boxOpaque(TaskPriority.background, typeName: "TaskPriority")),
    "var TaskPriority.description": .computed { receiver in
        let recv: TaskPriority = try unboxOpaque(receiver, as: TaskPriority.self, typeName: "TaskPriority")
        return .string(recv.description)
    },
    "init TaskPriority(_:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init TaskPriority(_:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = TaskPriority(try unboxOpaque(args[0], as: JobPriority.self, typeName: "JobPriority")) {
            return .optional(boxOpaque(_v, typeName: "TaskPriority"))
        }
        return .optional(nil)
    },
    ]
}
