// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let attributedStringIndex: [String: Bridge] = [
    "func AttributedString.Index.isValid()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AttributedString.Index.isValid: expected 1 argument(s), got \(args.count)")
        }
        let recv: AttributedString.Index = try unboxOpaque(receiver, as: AttributedString.Index.self, typeName: "AttributedString.Index")
        return .bool(recv.isValid(within: try unboxOpaque(args[0], as: DiscontiguousAttributedSubstring.self, typeName: "DiscontiguousAttributedSubstring")))
    },
    ]
}
