// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let formatStyleCapitalizationContext: [String: Bridge] = [
    "static let FormatStyleCapitalizationContext.unknown": .staticValue(boxOpaque(FormatStyleCapitalizationContext.unknown, typeName: "FormatStyleCapitalizationContext")),
    "static let FormatStyleCapitalizationContext.standalone": .staticValue(boxOpaque(FormatStyleCapitalizationContext.standalone, typeName: "FormatStyleCapitalizationContext")),
    "static let FormatStyleCapitalizationContext.listItem": .staticValue(boxOpaque(FormatStyleCapitalizationContext.listItem, typeName: "FormatStyleCapitalizationContext")),
    "static let FormatStyleCapitalizationContext.beginningOfSentence": .staticValue(boxOpaque(FormatStyleCapitalizationContext.beginningOfSentence, typeName: "FormatStyleCapitalizationContext")),
    "static let FormatStyleCapitalizationContext.middleOfSentence": .staticValue(boxOpaque(FormatStyleCapitalizationContext.middleOfSentence, typeName: "FormatStyleCapitalizationContext")),
    "var FormatStyleCapitalizationContext.hashValue": .computed { receiver in
        let recv: FormatStyleCapitalizationContext = try unboxOpaque(receiver, as: FormatStyleCapitalizationContext.self, typeName: "FormatStyleCapitalizationContext")
        return .int(recv.hashValue)
    },
    ]
}
