// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSFileVersionReplacingOptions: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["init NSFileVersion.ReplacingOptions()"] = .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSFileVersion.ReplacingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSFileVersion.ReplacingOptions(), typeName: "NSFileVersion.ReplacingOptions")
    }
    d["var NSFileVersion.ReplacingOptions.isEmpty: Bool"] = .computed { receiver in
        let recv: NSFileVersion.ReplacingOptions = try unboxOpaque(receiver, as: NSFileVersion.ReplacingOptions.self, typeName: "NSFileVersion.ReplacingOptions")
        return .bool(recv.isEmpty)
    }
    d["static let NSFileVersion.ReplacingOptions.byMoving"] = .staticValue(boxOpaque(NSFileVersion.ReplacingOptions.byMoving, typeName: "NSFileVersion.ReplacingOptions"))
        d["init NSFileVersion.ReplacingOptions(arrayLiteral:)"] = .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NSFileVersion.ReplacingOptions(arrayLiteral:): expected array literal")
            }
            var result = NSFileVersion.ReplacingOptions()
            for element in elements {
                let item: NSFileVersion.ReplacingOptions = try unboxOpaque(
                    element, as: NSFileVersion.ReplacingOptions.self, typeName: "NSFileVersion.ReplacingOptions"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NSFileVersion.ReplacingOptions")
        }
        #endif
        return d
    }()
}
