// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let jSONDecoder: [String: Bridge] = [
    "var JSONDecoder.allowsJSON5": .computed { receiver in
        let recv: JSONDecoder = try unboxOpaque(receiver, as: JSONDecoder.self, typeName: "JSONDecoder")
        return .bool(recv.allowsJSON5)
    },
    "var JSONDecoder.assumesTopLevelDictionary": .computed { receiver in
        let recv: JSONDecoder = try unboxOpaque(receiver, as: JSONDecoder.self, typeName: "JSONDecoder")
        return .bool(recv.assumesTopLevelDictionary)
    },
    "init JSONDecoder()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init JSONDecoder(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(JSONDecoder(), typeName: "JSONDecoder")
    },
    ]
}
