// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let notificationCenterObservationToken: [String: Bridge] = [
    "var NotificationCenter.ObservationToken.hashValue: Int": .computed { receiver in
        let recv: NotificationCenter.ObservationToken = try unboxOpaque(receiver, as: NotificationCenter.ObservationToken.self, typeName: "NotificationCenter.ObservationToken")
        return .int(recv.hashValue)
    },
    ]
}
