// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSDataBase64EncodingOptions: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["init NSData.Base64EncodingOptions()"] = .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSData.Base64EncodingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSData.Base64EncodingOptions(), typeName: "NSData.Base64EncodingOptions")
    }
    d["var NSData.Base64EncodingOptions.isEmpty: Bool"] = .computed { receiver in
        let recv: NSData.Base64EncodingOptions = try unboxOpaque(receiver, as: NSData.Base64EncodingOptions.self, typeName: "NSData.Base64EncodingOptions")
        return .bool(recv.isEmpty)
    }
    d["static let NSData.Base64EncodingOptions.lineLength64Characters"] = .staticValue(boxOpaque(NSData.Base64EncodingOptions.lineLength64Characters, typeName: "NSData.Base64EncodingOptions"))
    d["static let NSData.Base64EncodingOptions.lineLength76Characters"] = .staticValue(boxOpaque(NSData.Base64EncodingOptions.lineLength76Characters, typeName: "NSData.Base64EncodingOptions"))
    d["static let NSData.Base64EncodingOptions.endLineWithCarriageReturn"] = .staticValue(boxOpaque(NSData.Base64EncodingOptions.endLineWithCarriageReturn, typeName: "NSData.Base64EncodingOptions"))
    d["static let NSData.Base64EncodingOptions.endLineWithLineFeed"] = .staticValue(boxOpaque(NSData.Base64EncodingOptions.endLineWithLineFeed, typeName: "NSData.Base64EncodingOptions"))
        d["init NSData.Base64EncodingOptions(arrayLiteral:)"] = .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NSData.Base64EncodingOptions(arrayLiteral:): expected array literal")
            }
            var result = NSData.Base64EncodingOptions()
            for element in elements {
                let item: NSData.Base64EncodingOptions = try unboxOpaque(
                    element, as: NSData.Base64EncodingOptions.self, typeName: "NSData.Base64EncodingOptions"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NSData.Base64EncodingOptions")
        }
        #endif
        return d
    }()
}
