// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSRegularExpressionMatchingOptions: [String: Bridge] = [
    "init NSRegularExpression.MatchingOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSRegularExpression.MatchingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSRegularExpression.MatchingOptions(), typeName: "NSRegularExpression.MatchingOptions")
    },
    "var NSRegularExpression.MatchingOptions.isEmpty": .computed { receiver in
        let recv: NSRegularExpression.MatchingOptions = try unboxOpaque(receiver, as: NSRegularExpression.MatchingOptions.self, typeName: "NSRegularExpression.MatchingOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSRegularExpression.MatchingOptions.reportProgress": .staticValue(boxOpaque(NSRegularExpression.MatchingOptions.reportProgress, typeName: "NSRegularExpression.MatchingOptions")),
    "static let NSRegularExpression.MatchingOptions.reportCompletion": .staticValue(boxOpaque(NSRegularExpression.MatchingOptions.reportCompletion, typeName: "NSRegularExpression.MatchingOptions")),
    "static let NSRegularExpression.MatchingOptions.anchored": .staticValue(boxOpaque(NSRegularExpression.MatchingOptions.anchored, typeName: "NSRegularExpression.MatchingOptions")),
    "static let NSRegularExpression.MatchingOptions.withTransparentBounds": .staticValue(boxOpaque(NSRegularExpression.MatchingOptions.withTransparentBounds, typeName: "NSRegularExpression.MatchingOptions")),
    "static let NSRegularExpression.MatchingOptions.withoutAnchoringBounds": .staticValue(boxOpaque(NSRegularExpression.MatchingOptions.withoutAnchoringBounds, typeName: "NSRegularExpression.MatchingOptions")),
    ]
}
