// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let timeZone: [String: Bridge] = {
        var d: [String: Bridge] = [
    "static let TimeZone.timeZoneDataVersion": .staticValue(.string(TimeZone.timeZoneDataVersion)),
    "var TimeZone.nextDaylightSavingTimeTransition: Date?": .computed { receiver in
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        if let _v = recv.nextDaylightSavingTimeTransition {
            return .optional(boxOpaque(_v, typeName: "Date"))
        }
        return .optional(nil)
    },
    "var TimeZone.description: String": .computed { receiver in
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        return .string(recv.description)
    },
    "init TimeZone(identifier:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init TimeZone(identifier:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = TimeZone(identifier: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "TimeZone"))
        }
        return .optional(nil)
    },
    "init TimeZone(secondsFromGMT:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init TimeZone(secondsFromGMT:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = TimeZone(secondsFromGMT: try unboxInt(args[0])) {
            return .optional(boxOpaque(_v, typeName: "TimeZone"))
        }
        return .optional(nil)
    },
    "init TimeZone(abbreviation:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init TimeZone(abbreviation:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = TimeZone(abbreviation: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "TimeZone"))
        }
        return .optional(nil)
    },
    "func TimeZone.secondsFromGMT()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("TimeZone.secondsFromGMT: expected 1 argument(s), got \(args.count)")
        }
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        return .int(recv.secondsFromGMT(for: try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func TimeZone.abbreviation()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("TimeZone.abbreviation: expected 1 argument(s), got \(args.count)")
        }
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        if let _v = recv.abbreviation(for: try unboxOpaque(args[0], as: Date.self, typeName: "Date")) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "func TimeZone.isDaylightSavingTime()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("TimeZone.isDaylightSavingTime: expected 1 argument(s), got \(args.count)")
        }
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        return .bool(recv.isDaylightSavingTime(for: try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func TimeZone.daylightSavingTimeOffset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("TimeZone.daylightSavingTimeOffset: expected 1 argument(s), got \(args.count)")
        }
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        return .double(recv.daylightSavingTimeOffset(for: try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func TimeZone.nextDaylightSavingTimeTransition()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("TimeZone.nextDaylightSavingTimeTransition: expected 1 argument(s), got \(args.count)")
        }
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        if let _v = recv.nextDaylightSavingTimeTransition(after: try unboxOpaque(args[0], as: Date.self, typeName: "Date")) {
            return .optional(boxOpaque(_v, typeName: "Date"))
        }
        return .optional(nil)
    },
        ]
        #if canImport(Darwin)
    d["static let TimeZone.current"] = .staticValue(boxOpaque(TimeZone.current, typeName: "TimeZone"))
    d["static let TimeZone.autoupdatingCurrent"] = .staticValue(boxOpaque(TimeZone.autoupdatingCurrent, typeName: "TimeZone"))
    d["var TimeZone.identifier: String"] = .computed { receiver in
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        return .string(recv.identifier)
    }
    d["static let TimeZone.gmt"] = .staticValue(boxOpaque(TimeZone.gmt, typeName: "TimeZone"))
    d["var TimeZone.hashValue: Int"] = .computed { receiver in
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        return .int(recv.hashValue)
    }
    d["var TimeZone.debugDescription: String"] = .computed { receiver in
        let recv: TimeZone = try unboxOpaque(receiver, as: TimeZone.self, typeName: "TimeZone")
        return .string(recv.debugDescription)
    }
        #endif
        return d
    }()
}
