// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let unsafeCurrentTask: [String: Bridge] = [
    "var UnsafeCurrentTask.isCancelled: Bool": .computed { receiver in
        let recv: UnsafeCurrentTask = try unboxOpaque(receiver, as: UnsafeCurrentTask.self, typeName: "UnsafeCurrentTask")
        return .bool(recv.isCancelled)
    },
    "var UnsafeCurrentTask.priority: TaskPriority": .computed { receiver in
        let recv: UnsafeCurrentTask = try unboxOpaque(receiver, as: UnsafeCurrentTask.self, typeName: "UnsafeCurrentTask")
        return boxOpaque(recv.priority, typeName: "TaskPriority")
    },
    "var UnsafeCurrentTask.basePriority: TaskPriority": .computed { receiver in
        let recv: UnsafeCurrentTask = try unboxOpaque(receiver, as: UnsafeCurrentTask.self, typeName: "UnsafeCurrentTask")
        return boxOpaque(recv.basePriority, typeName: "TaskPriority")
    },
    "func UnsafeCurrentTask.cancel()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("UnsafeCurrentTask.cancel: expected 0 argument(s), got \(args.count)")
        }
        let recv: UnsafeCurrentTask = try unboxOpaque(receiver, as: UnsafeCurrentTask.self, typeName: "UnsafeCurrentTask")
        recv.cancel()
            return .void
    },
    "var UnsafeCurrentTask.hashValue: Int": .computed { receiver in
        let recv: UnsafeCurrentTask = try unboxOpaque(receiver, as: UnsafeCurrentTask.self, typeName: "UnsafeCurrentTask")
        return .int(recv.hashValue)
    },
    "var UnsafeCurrentTask.unownedTaskExecutor: UnownedTaskExecutor?": .computed { receiver in
        let recv: UnsafeCurrentTask = try unboxOpaque(receiver, as: UnsafeCurrentTask.self, typeName: "UnsafeCurrentTask")
        if let _v = recv.unownedTaskExecutor {
            return .optional(boxOpaque(_v, typeName: "UnownedTaskExecutor"))
        }
        return .optional(nil)
    },
    "func UnsafeCurrentTask.escalatePriority()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("UnsafeCurrentTask.escalatePriority: expected 1 argument(s), got \(args.count)")
        }
        let recv: UnsafeCurrentTask = try unboxOpaque(receiver, as: UnsafeCurrentTask.self, typeName: "UnsafeCurrentTask")
        recv.escalatePriority(to: try unboxOpaque(args[0], as: TaskPriority.self, typeName: "TaskPriority"))
            return .void
    },
    ]
}
