// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSFileVersionAddingOptions: [String: Bridge] = [
    "init NSFileVersion.AddingOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSFileVersion.AddingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSFileVersion.AddingOptions(), typeName: "NSFileVersion.AddingOptions")
    },
    "var NSFileVersion.AddingOptions.isEmpty": .computed { receiver in
        let recv: NSFileVersion.AddingOptions = try unboxOpaque(receiver, as: NSFileVersion.AddingOptions.self, typeName: "NSFileVersion.AddingOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSFileVersion.AddingOptions.byMoving": .staticValue(boxOpaque(NSFileVersion.AddingOptions.byMoving, typeName: "NSFileVersion.AddingOptions")),
    ]
}
