// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let nSFileVersionAddingOptions: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["init NSFileVersion.AddingOptions()"] = .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSFileVersion.AddingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSFileVersion.AddingOptions(), typeName: "NSFileVersion.AddingOptions")
    }
    d["var NSFileVersion.AddingOptions.isEmpty: Bool"] = .computed { receiver in
        let recv: NSFileVersion.AddingOptions = try unboxOpaque(receiver, as: NSFileVersion.AddingOptions.self, typeName: "NSFileVersion.AddingOptions")
        return .bool(recv.isEmpty)
    }
    d["static let NSFileVersion.AddingOptions.byMoving"] = .staticValue(boxOpaque(NSFileVersion.AddingOptions.byMoving, typeName: "NSFileVersion.AddingOptions"))
        d["init NSFileVersion.AddingOptions(arrayLiteral:)"] = .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NSFileVersion.AddingOptions(arrayLiteral:): expected array literal")
            }
            var result = NSFileVersion.AddingOptions()
            for element in elements {
                let item: NSFileVersion.AddingOptions = try unboxOpaque(
                    element, as: NSFileVersion.AddingOptions.self, typeName: "NSFileVersion.AddingOptions"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NSFileVersion.AddingOptions")
        }
        #endif
        return d
    }()
}
