// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let stringStyle: [String: Bridge] = [
    "var StringStyle.hashValue: Int": .computed { receiver in
        let recv: StringStyle = try unboxOpaque(receiver, as: StringStyle.self, typeName: "StringStyle")
        return .int(recv.hashValue)
    },
    "func StringStyle.locale()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("StringStyle.locale: expected 1 argument(s), got \(args.count)")
        }
        let recv: StringStyle = try unboxOpaque(receiver, as: StringStyle.self, typeName: "StringStyle")
        return boxOpaque(recv.locale(try unboxOpaque(args[0], as: Locale.self, typeName: "Locale")), typeName: "StringStyle")
    },
    "func StringStyle.format()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("StringStyle.format: expected 1 argument(s), got \(args.count)")
        }
        let recv: StringStyle = try unboxOpaque(receiver, as: StringStyle.self, typeName: "StringStyle")
        return .string(recv.format(try unboxString(args[0])))
    },
    ]
}
