// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSURLBookmarkCreationOptions: [String: Bridge] = [
    "init NSURL.BookmarkCreationOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSURL.BookmarkCreationOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSURL.BookmarkCreationOptions(), typeName: "NSURL.BookmarkCreationOptions")
    },
    "var NSURL.BookmarkCreationOptions.isEmpty": .computed { receiver in
        let recv: NSURL.BookmarkCreationOptions = try unboxOpaque(receiver, as: NSURL.BookmarkCreationOptions.self, typeName: "NSURL.BookmarkCreationOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSURL.BookmarkCreationOptions.minimalBookmark": .staticValue(boxOpaque(NSURL.BookmarkCreationOptions.minimalBookmark, typeName: "NSURL.BookmarkCreationOptions")),
    "static let NSURL.BookmarkCreationOptions.suitableForBookmarkFile": .staticValue(boxOpaque(NSURL.BookmarkCreationOptions.suitableForBookmarkFile, typeName: "NSURL.BookmarkCreationOptions")),
    "static let NSURL.BookmarkCreationOptions.withoutImplicitSecurityScope": .staticValue(boxOpaque(NSURL.BookmarkCreationOptions.withoutImplicitSecurityScope, typeName: "NSURL.BookmarkCreationOptions")),
    ]
}
