// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let errorUserInfoKey: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["var ErrorUserInfoKey.hashValue: Int"] = .computed { receiver in
        let recv: ErrorUserInfoKey = try unboxOpaque(receiver, as: ErrorUserInfoKey.self, typeName: "ErrorUserInfoKey")
        return .int(recv.hashValue)
    }
    d["var ErrorUserInfoKey.rawValue: String"] = .computed { receiver in
        let recv: ErrorUserInfoKey = try unboxOpaque(receiver, as: ErrorUserInfoKey.self, typeName: "ErrorUserInfoKey")
        return .string(recv.rawValue)
    }
    d["init ErrorUserInfoKey(rawValue:)"] = .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init ErrorUserInfoKey(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(ErrorUserInfoKey(rawValue: try unboxString(args[0])), typeName: "ErrorUserInfoKey")
    }
        #endif
        return d
    }()
}
