// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let fileManagerSearchPathDomainMask: [String: Bridge] = [
    "init FileManager.SearchPathDomainMask()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init FileManager.SearchPathDomainMask(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(FileManager.SearchPathDomainMask(), typeName: "FileManager.SearchPathDomainMask")
    },
    "var FileManager.SearchPathDomainMask.isEmpty": .computed { receiver in
        let recv: FileManager.SearchPathDomainMask = try unboxOpaque(receiver, as: FileManager.SearchPathDomainMask.self, typeName: "FileManager.SearchPathDomainMask")
        return .bool(recv.isEmpty)
    },
    "static let FileManager.SearchPathDomainMask.userDomainMask": .staticValue(boxOpaque(FileManager.SearchPathDomainMask.userDomainMask, typeName: "FileManager.SearchPathDomainMask")),
    "static let FileManager.SearchPathDomainMask.localDomainMask": .staticValue(boxOpaque(FileManager.SearchPathDomainMask.localDomainMask, typeName: "FileManager.SearchPathDomainMask")),
    "static let FileManager.SearchPathDomainMask.networkDomainMask": .staticValue(boxOpaque(FileManager.SearchPathDomainMask.networkDomainMask, typeName: "FileManager.SearchPathDomainMask")),
    "static let FileManager.SearchPathDomainMask.systemDomainMask": .staticValue(boxOpaque(FileManager.SearchPathDomainMask.systemDomainMask, typeName: "FileManager.SearchPathDomainMask")),
    "static let FileManager.SearchPathDomainMask.allDomainsMask": .staticValue(boxOpaque(FileManager.SearchPathDomainMask.allDomainsMask, typeName: "FileManager.SearchPathDomainMask")),
    ]
}
