// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSDataReadingOptions: [String: Bridge] = [
    "init NSData.ReadingOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSData.ReadingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSData.ReadingOptions(), typeName: "NSData.ReadingOptions")
    },
    "var NSData.ReadingOptions.isEmpty": .computed { receiver in
        let recv: NSData.ReadingOptions = try unboxOpaque(receiver, as: NSData.ReadingOptions.self, typeName: "NSData.ReadingOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSData.ReadingOptions.mappedIfSafe": .staticValue(boxOpaque(NSData.ReadingOptions.mappedIfSafe, typeName: "NSData.ReadingOptions")),
    "static let NSData.ReadingOptions.uncached": .staticValue(boxOpaque(NSData.ReadingOptions.uncached, typeName: "NSData.ReadingOptions")),
    "static let NSData.ReadingOptions.alwaysMapped": .staticValue(boxOpaque(NSData.ReadingOptions.alwaysMapped, typeName: "NSData.ReadingOptions")),
    "static let NSData.ReadingOptions.dataReadingMapped": .staticValue(boxOpaque(NSData.ReadingOptions.dataReadingMapped, typeName: "NSData.ReadingOptions")),
    "static let NSData.ReadingOptions.mappedRead": .staticValue(boxOpaque(NSData.ReadingOptions.mappedRead, typeName: "NSData.ReadingOptions")),
    "static let NSData.ReadingOptions.uncachedRead": .staticValue(boxOpaque(NSData.ReadingOptions.uncachedRead, typeName: "NSData.ReadingOptions")),
    ]
}
