// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSFileCoordinatorWritingOptions: [String: Bridge] = [
    "init NSFileCoordinator.WritingOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSFileCoordinator.WritingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSFileCoordinator.WritingOptions(), typeName: "NSFileCoordinator.WritingOptions")
    },
    "var NSFileCoordinator.WritingOptions.isEmpty": .computed { receiver in
        let recv: NSFileCoordinator.WritingOptions = try unboxOpaque(receiver, as: NSFileCoordinator.WritingOptions.self, typeName: "NSFileCoordinator.WritingOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSFileCoordinator.WritingOptions.forDeleting": .staticValue(boxOpaque(NSFileCoordinator.WritingOptions.forDeleting, typeName: "NSFileCoordinator.WritingOptions")),
    "static let NSFileCoordinator.WritingOptions.forMoving": .staticValue(boxOpaque(NSFileCoordinator.WritingOptions.forMoving, typeName: "NSFileCoordinator.WritingOptions")),
    "static let NSFileCoordinator.WritingOptions.forMerging": .staticValue(boxOpaque(NSFileCoordinator.WritingOptions.forMerging, typeName: "NSFileCoordinator.WritingOptions")),
    "static let NSFileCoordinator.WritingOptions.forReplacing": .staticValue(boxOpaque(NSFileCoordinator.WritingOptions.forReplacing, typeName: "NSFileCoordinator.WritingOptions")),
    "static let NSFileCoordinator.WritingOptions.contentIndependentMetadataOnly": .staticValue(boxOpaque(NSFileCoordinator.WritingOptions.contentIndependentMetadataOnly, typeName: "NSFileCoordinator.WritingOptions")),
    ]
}
