// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let nSDataBase64DecodingOptions: [String: Bridge] = [
    "init NSData.Base64DecodingOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSData.Base64DecodingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSData.Base64DecodingOptions(), typeName: "NSData.Base64DecodingOptions")
    },
    "var NSData.Base64DecodingOptions.isEmpty": .computed { receiver in
        let recv: NSData.Base64DecodingOptions = try unboxOpaque(receiver, as: NSData.Base64DecodingOptions.self, typeName: "NSData.Base64DecodingOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSData.Base64DecodingOptions.ignoreUnknownCharacters": .staticValue(boxOpaque(NSData.Base64DecodingOptions.ignoreUnknownCharacters, typeName: "NSData.Base64DecodingOptions")),
    ]
}
