// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let attributedStringAttributeInvalidationCondition: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["static let AttributedString.AttributeInvalidationCondition.textChanged"] = .staticValue(boxOpaque(AttributedString.AttributeInvalidationCondition.textChanged, typeName: "AttributedString.AttributeInvalidationCondition"))
    d["var AttributedString.AttributeInvalidationCondition.hashValue: Int"] = .computed { receiver in
        let recv: AttributedString.AttributeInvalidationCondition = try unboxOpaque(receiver, as: AttributedString.AttributeInvalidationCondition.self, typeName: "AttributedString.AttributeInvalidationCondition")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
