// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let uRLSession: [String: Bridge] = [
    "static let URLSession.shared": .staticValue(boxOpaque(URLSession.shared, typeName: "URLSession")),
    "var URLSession.sessionDescription: String?": .computed { receiver in
        let recv: URLSession = try unboxOpaque(receiver, as: URLSession.self, typeName: "URLSession")
        if let _v = recv.sessionDescription {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "func URLSession.data()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URLSession.data: expected 1 argument(s), got \(args.count)")
        }
        let recv: URLSession = try unboxOpaque(receiver, as: URLSession.self, typeName: "URLSession")
        do {
            let _t = try await recv.data(from: try unboxOpaque(args[0], as: URL.self, typeName: "URL"))
        return .tuple([boxOpaque(_t.0, typeName: "Data"), boxOpaque(_t.1, typeName: "URLResponse")])
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func URLSession.upload()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("URLSession.upload: expected 2 argument(s), got \(args.count)")
        }
        let recv: URLSession = try unboxOpaque(receiver, as: URLSession.self, typeName: "URLSession")
        do {
            let _t = try await recv.upload(for: try unboxOpaque(args[0], as: URLRequest.self, typeName: "URLRequest"), fromFile: try unboxOpaque(args[1], as: URL.self, typeName: "URL"))
        return .tuple([boxOpaque(_t.0, typeName: "Data"), boxOpaque(_t.1, typeName: "URLResponse")])
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    ]
}
