// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let fileWrapperReadingOptions: [String: Bridge] = [
    "init FileWrapper.ReadingOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init FileWrapper.ReadingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(FileWrapper.ReadingOptions(), typeName: "FileWrapper.ReadingOptions")
    },
    "var FileWrapper.ReadingOptions.isEmpty": .computed { receiver in
        let recv: FileWrapper.ReadingOptions = try unboxOpaque(receiver, as: FileWrapper.ReadingOptions.self, typeName: "FileWrapper.ReadingOptions")
        return .bool(recv.isEmpty)
    },
    "static let FileWrapper.ReadingOptions.immediate": .staticValue(boxOpaque(FileWrapper.ReadingOptions.immediate, typeName: "FileWrapper.ReadingOptions")),
    "static let FileWrapper.ReadingOptions.withoutMapping": .staticValue(boxOpaque(FileWrapper.ReadingOptions.withoutMapping, typeName: "FileWrapper.ReadingOptions")),
    ]
}
