// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let uRLResource: [String: Bridge] = [
    "var URLResource.name": .computed { receiver in
        let recv: URLResource = try unboxOpaque(receiver, as: URLResource.self, typeName: "URLResource")
        return .string(recv.name)
    },
    "var URLResource.subdirectory": .computed { receiver in
        let recv: URLResource = try unboxOpaque(receiver, as: URLResource.self, typeName: "URLResource")
        if let _v = recv.subdirectory {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLResource.locale": .computed { receiver in
        let recv: URLResource = try unboxOpaque(receiver, as: URLResource.self, typeName: "URLResource")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "var URLResource.hashValue": .computed { receiver in
        let recv: URLResource = try unboxOpaque(receiver, as: URLResource.self, typeName: "URLResource")
        return .int(recv.hashValue)
    },
    ]
}
