#if canImport(Darwin)
// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let streamNetworkServiceTypeValue: [String: Bridge] = [
    "var StreamNetworkServiceTypeValue.hashValue: Int": .computed { receiver in
        let recv: StreamNetworkServiceTypeValue = try unboxOpaque(receiver, as: StreamNetworkServiceTypeValue.self, typeName: "StreamNetworkServiceTypeValue")
        return .int(recv.hashValue)
    },
    "static let StreamNetworkServiceTypeValue.voIP": .staticValue(boxOpaque(StreamNetworkServiceTypeValue.voIP, typeName: "StreamNetworkServiceTypeValue")),
    "static let StreamNetworkServiceTypeValue.video": .staticValue(boxOpaque(StreamNetworkServiceTypeValue.video, typeName: "StreamNetworkServiceTypeValue")),
    "static let StreamNetworkServiceTypeValue.background": .staticValue(boxOpaque(StreamNetworkServiceTypeValue.background, typeName: "StreamNetworkServiceTypeValue")),
    "static let StreamNetworkServiceTypeValue.voice": .staticValue(boxOpaque(StreamNetworkServiceTypeValue.voice, typeName: "StreamNetworkServiceTypeValue")),
    "static let StreamNetworkServiceTypeValue.callSignaling": .staticValue(boxOpaque(StreamNetworkServiceTypeValue.callSignaling, typeName: "StreamNetworkServiceTypeValue")),
    "init StreamNetworkServiceTypeValue(rawValue:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init StreamNetworkServiceTypeValue(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(StreamNetworkServiceTypeValue(rawValue: try unboxString(args[0])), typeName: "StreamNetworkServiceTypeValue")
    },
    ]
}
#endif
