// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let uRLComponents: [String: Bridge] = [
    "init URLComponents()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init URLComponents(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(URLComponents(), typeName: "URLComponents")
    },
    "var URLComponents.url": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.url {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "var URLComponents.string": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.string {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.scheme": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.scheme {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.user": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.user {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.password": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.password {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.host": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.host {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.port": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.port {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.path": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .string(recv.path)
    },
    "var URLComponents.query": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.query {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.fragment": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.fragment {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedUser": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedUser {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedPassword": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedPassword {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedHost": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedHost {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.encodedHost": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.encodedHost {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedPath": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .string(recv.percentEncodedPath)
    },
    "var URLComponents.percentEncodedQuery": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedQuery {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedFragment": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedFragment {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.hashValue": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .int(recv.hashValue)
    },
    "var URLComponents.description": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .string(recv.description)
    },
    "var URLComponents.debugDescription": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .string(recv.debugDescription)
    },
    "init URLComponents(string:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init URLComponents(string:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = URLComponents(string: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "URLComponents"))
        }
        return .optional(nil)
    },
    "init URLComponents(url:resolvingAgainstBaseURL:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init URLComponents(url:resolvingAgainstBaseURL:): expected 2 argument(s), got \(args.count)")
        }
        if let _v = URLComponents(url: try unboxOpaque(args[0], as: URL.self, typeName: "URL"), resolvingAgainstBaseURL: try unboxBool(args[1])) {
            return .optional(boxOpaque(_v, typeName: "URLComponents"))
        }
        return .optional(nil)
    },
    "init URLComponents(string:encodingInvalidCharacters:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init URLComponents(string:encodingInvalidCharacters:): expected 2 argument(s), got \(args.count)")
        }
        if let _v = URLComponents(string: try unboxString(args[0]), encodingInvalidCharacters: try unboxBool(args[1])) {
            return .optional(boxOpaque(_v, typeName: "URLComponents"))
        }
        return .optional(nil)
    },
    ]
}
