// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let affineTransform: [String: Bridge] = [
    "init AffineTransform()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init AffineTransform(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(AffineTransform(), typeName: "AffineTransform")
    },
    "static let AffineTransform.identity": .staticValue(boxOpaque(AffineTransform.identity, typeName: "AffineTransform")),
    "func AffineTransform.inverted()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("AffineTransform.inverted: expected 0 argument(s), got \(args.count)")
        }
        let recv: AffineTransform = try unboxOpaque(receiver, as: AffineTransform.self, typeName: "AffineTransform")
        if let _v = recv.inverted() {
            return .optional(boxOpaque(_v, typeName: "AffineTransform"))
        }
        return .optional(nil)
    },
    "var AffineTransform.description": .computed { receiver in
        let recv: AffineTransform = try unboxOpaque(receiver, as: AffineTransform.self, typeName: "AffineTransform")
        return .string(recv.description)
    },
    "var AffineTransform.debugDescription": .computed { receiver in
        let recv: AffineTransform = try unboxOpaque(receiver, as: AffineTransform.self, typeName: "AffineTransform")
        return .string(recv.debugDescription)
    },
    "var AffineTransform.hashValue": .computed { receiver in
        let recv: AffineTransform = try unboxOpaque(receiver, as: AffineTransform.self, typeName: "AffineTransform")
        return .int(recv.hashValue)
    },
    ]
}
