// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let localeCollation: [String: Bridge] = [
    "var Locale.Collation.identifier": .computed { receiver in
        let recv: Locale.Collation = try unboxOpaque(receiver, as: Locale.Collation.self, typeName: "Locale.Collation")
        return .string(recv.identifier)
    },
    "var Locale.Collation.debugDescription": .computed { receiver in
        let recv: Locale.Collation = try unboxOpaque(receiver, as: Locale.Collation.self, typeName: "Locale.Collation")
        return .string(recv.debugDescription)
    },
    "static let Locale.Collation.searchRules": .staticValue(boxOpaque(Locale.Collation.searchRules, typeName: "Locale.Collation")),
    "static let Locale.Collation.standard": .staticValue(boxOpaque(Locale.Collation.standard, typeName: "Locale.Collation")),
    "var Locale.Collation.hashValue": .computed { receiver in
        let recv: Locale.Collation = try unboxOpaque(receiver, as: Locale.Collation.self, typeName: "Locale.Collation")
        return .int(recv.hashValue)
    },
    "init Locale.Collation(stringLiteral:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Locale.Collation(stringLiteral:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(Locale.Collation(stringLiteral: try unboxString(args[0])), typeName: "Locale.Collation")
    },
    "init Locale.Collation(_:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Locale.Collation(_:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(Locale.Collation(try unboxString(args[0])), typeName: "Locale.Collation")
    },
    ]
}
