// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let uRLTemplate: [String: Bridge] = [
    "var URL.Template.hashValue: Int": .computed { receiver in
        let recv: URL.Template = try unboxOpaque(receiver, as: URL.Template.self, typeName: "URL.Template")
        return .int(recv.hashValue)
    },
    "var URL.Template.description: String": .computed { receiver in
        let recv: URL.Template = try unboxOpaque(receiver, as: URL.Template.self, typeName: "URL.Template")
        return .string(recv.description)
    },
    "init URL.Template(_:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init URL.Template(_:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = URL.Template(try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "URL.Template"))
        }
        return .optional(nil)
    },
    ]
}
