// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let byteCountFormatStyle: [String: Bridge] = [
    "var ByteCountFormatStyle.allowedUnits": .computed { receiver in
        let recv: ByteCountFormatStyle = try unboxOpaque(receiver, as: ByteCountFormatStyle.self, typeName: "ByteCountFormatStyle")
        return boxOpaque(recv.allowedUnits, typeName: "ByteCountFormatStyle.Units")
    },
    "var ByteCountFormatStyle.spellsOutZero": .computed { receiver in
        let recv: ByteCountFormatStyle = try unboxOpaque(receiver, as: ByteCountFormatStyle.self, typeName: "ByteCountFormatStyle")
        return .bool(recv.spellsOutZero)
    },
    "var ByteCountFormatStyle.includesActualByteCount": .computed { receiver in
        let recv: ByteCountFormatStyle = try unboxOpaque(receiver, as: ByteCountFormatStyle.self, typeName: "ByteCountFormatStyle")
        return .bool(recv.includesActualByteCount)
    },
    "var ByteCountFormatStyle.locale": .computed { receiver in
        let recv: ByteCountFormatStyle = try unboxOpaque(receiver, as: ByteCountFormatStyle.self, typeName: "ByteCountFormatStyle")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "var ByteCountFormatStyle.attributed": .computed { receiver in
        let recv: ByteCountFormatStyle = try unboxOpaque(receiver, as: ByteCountFormatStyle.self, typeName: "ByteCountFormatStyle")
        return boxOpaque(recv.attributed, typeName: "ByteCountFormatStyle.Attributed")
    },
    "var ByteCountFormatStyle.hashValue": .computed { receiver in
        let recv: ByteCountFormatStyle = try unboxOpaque(receiver, as: ByteCountFormatStyle.self, typeName: "ByteCountFormatStyle")
        return .int(recv.hashValue)
    },
    "func ByteCountFormatStyle.locale()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("ByteCountFormatStyle.locale: expected 1 argument(s), got \(args.count)")
        }
        let recv: ByteCountFormatStyle = try unboxOpaque(receiver, as: ByteCountFormatStyle.self, typeName: "ByteCountFormatStyle")
        return boxOpaque(recv.locale(try unboxOpaque(args[0], as: Locale.self, typeName: "Locale")), typeName: "ByteCountFormatStyle")
    },
    "init ByteCountFormatStyle(allowedUnits:spellsOutZero:includesActualByteCount:locale:)": .`init` { args in
        guard args.count == 4 else {
            throw RuntimeError.invalid("init ByteCountFormatStyle(allowedUnits:spellsOutZero:includesActualByteCount:locale:): expected 4 argument(s), got \(args.count)")
        }
        return boxOpaque(ByteCountFormatStyle(allowedUnits: try unboxOpaque(args[0], as: ByteCountFormatStyle.Units.self, typeName: "ByteCountFormatStyle.Units"), spellsOutZero: try unboxBool(args[1]), includesActualByteCount: try unboxBool(args[2]), locale: try unboxOpaque(args[3], as: Locale.self, typeName: "Locale")), typeName: "ByteCountFormatStyle")
    },
    ]
}
