// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let discontiguousAttributedSubstring: [String: Bridge] = [
    "var DiscontiguousAttributedSubstring.base": .computed { receiver in
        let recv: DiscontiguousAttributedSubstring = try unboxOpaque(receiver, as: DiscontiguousAttributedSubstring.self, typeName: "DiscontiguousAttributedSubstring")
        return boxOpaque(recv.base, typeName: "AttributedString")
    },
    "var DiscontiguousAttributedSubstring.description": .computed { receiver in
        let recv: DiscontiguousAttributedSubstring = try unboxOpaque(receiver, as: DiscontiguousAttributedSubstring.self, typeName: "DiscontiguousAttributedSubstring")
        return .string(recv.description)
    },
    "var DiscontiguousAttributedSubstring.hashValue": .computed { receiver in
        let recv: DiscontiguousAttributedSubstring = try unboxOpaque(receiver, as: DiscontiguousAttributedSubstring.self, typeName: "DiscontiguousAttributedSubstring")
        return .int(recv.hashValue)
    },
    "var DiscontiguousAttributedSubstring.runs": .computed { receiver in
        let recv: DiscontiguousAttributedSubstring = try unboxOpaque(receiver, as: DiscontiguousAttributedSubstring.self, typeName: "DiscontiguousAttributedSubstring")
        return boxOpaque(recv.runs, typeName: "AttributedString.Runs")
    },
    ]
}
