// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let numberFormatStyleConfigurationGrouping: [String: Bridge] = [
    "static let NumberFormatStyleConfiguration.Grouping.automatic": .staticValue(boxOpaque(NumberFormatStyleConfiguration.Grouping.automatic, typeName: "NumberFormatStyleConfiguration.Grouping")),
    "static let NumberFormatStyleConfiguration.Grouping.never": .staticValue(boxOpaque(NumberFormatStyleConfiguration.Grouping.never, typeName: "NumberFormatStyleConfiguration.Grouping")),
    "var NumberFormatStyleConfiguration.Grouping.description: String": .computed { receiver in
        let recv: NumberFormatStyleConfiguration.Grouping = try unboxOpaque(receiver, as: NumberFormatStyleConfiguration.Grouping.self, typeName: "NumberFormatStyleConfiguration.Grouping")
        return .string(recv.description)
    },
    "var NumberFormatStyleConfiguration.Grouping.hashValue: Int": .computed { receiver in
        let recv: NumberFormatStyleConfiguration.Grouping = try unboxOpaque(receiver, as: NumberFormatStyleConfiguration.Grouping.self, typeName: "NumberFormatStyleConfiguration.Grouping")
        return .int(recv.hashValue)
    },
    ]
}
