// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let fileWrapperWritingOptions: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["init FileWrapper.WritingOptions()"] = .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init FileWrapper.WritingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(FileWrapper.WritingOptions(), typeName: "FileWrapper.WritingOptions")
    }
    d["var FileWrapper.WritingOptions.isEmpty: Bool"] = .computed { receiver in
        let recv: FileWrapper.WritingOptions = try unboxOpaque(receiver, as: FileWrapper.WritingOptions.self, typeName: "FileWrapper.WritingOptions")
        return .bool(recv.isEmpty)
    }
    d["static let FileWrapper.WritingOptions.atomic"] = .staticValue(boxOpaque(FileWrapper.WritingOptions.atomic, typeName: "FileWrapper.WritingOptions"))
    d["static let FileWrapper.WritingOptions.withNameUpdating"] = .staticValue(boxOpaque(FileWrapper.WritingOptions.withNameUpdating, typeName: "FileWrapper.WritingOptions"))
        d["init FileWrapper.WritingOptions(arrayLiteral:)"] = .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("FileWrapper.WritingOptions(arrayLiteral:): expected array literal")
            }
            var result = FileWrapper.WritingOptions()
            for element in elements {
                let item: FileWrapper.WritingOptions = try unboxOpaque(
                    element, as: FileWrapper.WritingOptions.self, typeName: "FileWrapper.WritingOptions"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "FileWrapper.WritingOptions")
        }
        #endif
        return d
    }()
}
