// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let attributedStringFormattingOptions: [String: Bridge] = [
    "init AttributedString.FormattingOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init AttributedString.FormattingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(AttributedString.FormattingOptions(), typeName: "AttributedString.FormattingOptions")
    },
    "var AttributedString.FormattingOptions.isEmpty": .computed { receiver in
        let recv: AttributedString.FormattingOptions = try unboxOpaque(receiver, as: AttributedString.FormattingOptions.self, typeName: "AttributedString.FormattingOptions")
        return .bool(recv.isEmpty)
    },
    "static let AttributedString.FormattingOptions.applyReplacementIndexAttribute": .staticValue(boxOpaque(AttributedString.FormattingOptions.applyReplacementIndexAttribute, typeName: "AttributedString.FormattingOptions")),
    ]
}
