// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let predicateExpressionsVariableID: [String: Bridge] = [
    "var PredicateExpressions.VariableID.hashValue": .computed { receiver in
        let recv: PredicateExpressions.VariableID = try unboxOpaque(receiver, as: PredicateExpressions.VariableID.self, typeName: "PredicateExpressions.VariableID")
        return .int(recv.hashValue)
    },
    ]
}
