// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let propertyListEncoder: [String: Bridge] = [
        "func PropertyListEncoder.encode<Value: Encodable>(_: Value) throws -> Data": .method { receiver, args in
            guard args.count == 1 else {
                throw RuntimeError.invalid("PropertyListEncoder.encode: expected 1 argument(s), got \(args.count)")
            }
            let recv: PropertyListEncoder = try unboxOpaque(receiver, as: PropertyListEncoder.self, typeName: "PropertyListEncoder")
            do {
                return .opaque(typeName: "Data", value: try recv.encode(ScriptCodable(args[0])))
            } catch {
                throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
            }
        },
    ]
}
