// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    static let alignmentOptions: [String: Bridge] = [
    "init AlignmentOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init AlignmentOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(AlignmentOptions(), typeName: "AlignmentOptions")
    },
    "var AlignmentOptions.isEmpty": .computed { receiver in
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return .bool(recv.isEmpty)
    },
    "static let AlignmentOptions.alignMinXInward": .staticValue(boxOpaque(AlignmentOptions.alignMinXInward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMinYInward": .staticValue(boxOpaque(AlignmentOptions.alignMinYInward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMaxXInward": .staticValue(boxOpaque(AlignmentOptions.alignMaxXInward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMaxYInward": .staticValue(boxOpaque(AlignmentOptions.alignMaxYInward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignWidthInward": .staticValue(boxOpaque(AlignmentOptions.alignWidthInward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignHeightInward": .staticValue(boxOpaque(AlignmentOptions.alignHeightInward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMinXOutward": .staticValue(boxOpaque(AlignmentOptions.alignMinXOutward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMinYOutward": .staticValue(boxOpaque(AlignmentOptions.alignMinYOutward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMaxXOutward": .staticValue(boxOpaque(AlignmentOptions.alignMaxXOutward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMaxYOutward": .staticValue(boxOpaque(AlignmentOptions.alignMaxYOutward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignWidthOutward": .staticValue(boxOpaque(AlignmentOptions.alignWidthOutward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignHeightOutward": .staticValue(boxOpaque(AlignmentOptions.alignHeightOutward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMinXNearest": .staticValue(boxOpaque(AlignmentOptions.alignMinXNearest, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMinYNearest": .staticValue(boxOpaque(AlignmentOptions.alignMinYNearest, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMaxXNearest": .staticValue(boxOpaque(AlignmentOptions.alignMaxXNearest, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignMaxYNearest": .staticValue(boxOpaque(AlignmentOptions.alignMaxYNearest, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignWidthNearest": .staticValue(boxOpaque(AlignmentOptions.alignWidthNearest, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignHeightNearest": .staticValue(boxOpaque(AlignmentOptions.alignHeightNearest, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignRectFlipped": .staticValue(boxOpaque(AlignmentOptions.alignRectFlipped, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignAllEdgesInward": .staticValue(boxOpaque(AlignmentOptions.alignAllEdgesInward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignAllEdgesOutward": .staticValue(boxOpaque(AlignmentOptions.alignAllEdgesOutward, typeName: "AlignmentOptions")),
    "static let AlignmentOptions.alignAllEdgesNearest": .staticValue(boxOpaque(AlignmentOptions.alignAllEdgesNearest, typeName: "AlignmentOptions")),
    "func AlignmentOptions.union()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.union: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return boxOpaque(recv.union(try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")), typeName: "AlignmentOptions")
    },
    "func AlignmentOptions.intersection()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.intersection: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return boxOpaque(recv.intersection(try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")), typeName: "AlignmentOptions")
    },
    "func AlignmentOptions.symmetricDifference()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.symmetricDifference: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return boxOpaque(recv.symmetricDifference(try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")), typeName: "AlignmentOptions")
    },
    "func AlignmentOptions.contains()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.contains: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return .bool(recv.contains(try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")))
    },
    "func AlignmentOptions.isSubset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.isSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return .bool(recv.isSubset(of: try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")))
    },
    "func AlignmentOptions.isSuperset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.isSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return .bool(recv.isSuperset(of: try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")))
    },
    "func AlignmentOptions.isDisjoint()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.isDisjoint: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return .bool(recv.isDisjoint(with: try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")))
    },
    "func AlignmentOptions.subtracting()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.subtracting: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return boxOpaque(recv.subtracting(try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")), typeName: "AlignmentOptions")
    },
    "func AlignmentOptions.isStrictSuperset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.isStrictSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return .bool(recv.isStrictSuperset(of: try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")))
    },
    "func AlignmentOptions.isStrictSubset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AlignmentOptions.isStrictSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: AlignmentOptions = try unboxOpaque(receiver, as: AlignmentOptions.self, typeName: "AlignmentOptions")
        return .bool(recv.isStrictSubset(of: try unboxOpaque(args[0], as: AlignmentOptions.self, typeName: "AlignmentOptions")))
    },
    ]
}
