// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let netServiceOptions: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["init NetService.Options()"] = .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NetService.Options(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NetService.Options(), typeName: "NetService.Options")
    }
    d["var NetService.Options.isEmpty: Bool"] = .computed { receiver in
        let recv: NetService.Options = try unboxOpaque(receiver, as: NetService.Options.self, typeName: "NetService.Options")
        return .bool(recv.isEmpty)
    }
    d["static let NetService.Options.noAutoRename"] = .staticValue(boxOpaque(NetService.Options.noAutoRename, typeName: "NetService.Options"))
    d["static let NetService.Options.listenForConnections"] = .staticValue(boxOpaque(NetService.Options.listenForConnections, typeName: "NetService.Options"))
        d["init NetService.Options(arrayLiteral:)"] = .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NetService.Options(arrayLiteral:): expected array literal")
            }
            var result = NetService.Options()
            for element in elements {
                let item: NetService.Options = try unboxOpaque(
                    element, as: NetService.Options.self, typeName: "NetService.Options"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NetService.Options")
        }
        #endif
        return d
    }()
}
