// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let stringEncodingDetectionOptionsKey: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["var StringEncodingDetectionOptionsKey.hashValue: Int"] = .computed { receiver in
        let recv: StringEncodingDetectionOptionsKey = try unboxOpaque(receiver, as: StringEncodingDetectionOptionsKey.self, typeName: "StringEncodingDetectionOptionsKey")
        return .int(recv.hashValue)
    }
    d["static let StringEncodingDetectionOptionsKey.suggestedEncodingsKey"] = .staticValue(boxOpaque(StringEncodingDetectionOptionsKey.suggestedEncodingsKey, typeName: "StringEncodingDetectionOptionsKey"))
    d["static let StringEncodingDetectionOptionsKey.disallowedEncodingsKey"] = .staticValue(boxOpaque(StringEncodingDetectionOptionsKey.disallowedEncodingsKey, typeName: "StringEncodingDetectionOptionsKey"))
    d["static let StringEncodingDetectionOptionsKey.useOnlySuggestedEncodingsKey"] = .staticValue(boxOpaque(StringEncodingDetectionOptionsKey.useOnlySuggestedEncodingsKey, typeName: "StringEncodingDetectionOptionsKey"))
    d["static let StringEncodingDetectionOptionsKey.allowLossyKey"] = .staticValue(boxOpaque(StringEncodingDetectionOptionsKey.allowLossyKey, typeName: "StringEncodingDetectionOptionsKey"))
    d["static let StringEncodingDetectionOptionsKey.fromWindowsKey"] = .staticValue(boxOpaque(StringEncodingDetectionOptionsKey.fromWindowsKey, typeName: "StringEncodingDetectionOptionsKey"))
    d["static let StringEncodingDetectionOptionsKey.lossySubstitutionKey"] = .staticValue(boxOpaque(StringEncodingDetectionOptionsKey.lossySubstitutionKey, typeName: "StringEncodingDetectionOptionsKey"))
    d["static let StringEncodingDetectionOptionsKey.likelyLanguageKey"] = .staticValue(boxOpaque(StringEncodingDetectionOptionsKey.likelyLanguageKey, typeName: "StringEncodingDetectionOptionsKey"))
    d["init StringEncodingDetectionOptionsKey(rawValue:)"] = .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init StringEncodingDetectionOptionsKey(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(StringEncodingDetectionOptionsKey(rawValue: try unboxString(args[0])), typeName: "StringEncodingDetectionOptionsKey")
    }
        #endif
        return d
    }()
}
