// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let nSFileManagerSupportedSyncControls: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["init NSFileManagerSupportedSyncControls()"] = .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSFileManagerSupportedSyncControls(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSFileManagerSupportedSyncControls(), typeName: "NSFileManagerSupportedSyncControls")
    }
    d["var NSFileManagerSupportedSyncControls.isEmpty: Bool"] = .computed { receiver in
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isEmpty)
    }
    d["static let NSFileManagerSupportedSyncControls.pauseSync"] = .staticValue(boxOpaque(NSFileManagerSupportedSyncControls.pauseSync, typeName: "NSFileManagerSupportedSyncControls"))
    d["static let NSFileManagerSupportedSyncControls.failUploadOnConflict"] = .staticValue(boxOpaque(NSFileManagerSupportedSyncControls.failUploadOnConflict, typeName: "NSFileManagerSupportedSyncControls"))
    d["func NSFileManagerSupportedSyncControls.union()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.union: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return boxOpaque(recv.union(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")), typeName: "NSFileManagerSupportedSyncControls")
    }
    d["func NSFileManagerSupportedSyncControls.intersection()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.intersection: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return boxOpaque(recv.intersection(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")), typeName: "NSFileManagerSupportedSyncControls")
    }
    d["func NSFileManagerSupportedSyncControls.symmetricDifference()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.symmetricDifference: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return boxOpaque(recv.symmetricDifference(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")), typeName: "NSFileManagerSupportedSyncControls")
    }
    d["func NSFileManagerSupportedSyncControls.contains()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.contains: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.contains(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    }
    d["func NSFileManagerSupportedSyncControls.isSubset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isSubset(of: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    }
    d["func NSFileManagerSupportedSyncControls.isSuperset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isSuperset(of: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    }
    d["func NSFileManagerSupportedSyncControls.isDisjoint()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isDisjoint: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isDisjoint(with: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    }
    d["func NSFileManagerSupportedSyncControls.subtracting()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.subtracting: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return boxOpaque(recv.subtracting(try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")), typeName: "NSFileManagerSupportedSyncControls")
    }
    d["func NSFileManagerSupportedSyncControls.isStrictSuperset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isStrictSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isStrictSuperset(of: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    }
    d["func NSFileManagerSupportedSyncControls.isStrictSubset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSFileManagerSupportedSyncControls.isStrictSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSFileManagerSupportedSyncControls = try unboxOpaque(receiver, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")
        return .bool(recv.isStrictSubset(of: try unboxOpaque(args[0], as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls")))
    }
        d["init NSFileManagerSupportedSyncControls(arrayLiteral:)"] = .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NSFileManagerSupportedSyncControls(arrayLiteral:): expected array literal")
            }
            var result = NSFileManagerSupportedSyncControls()
            for element in elements {
                let item: NSFileManagerSupportedSyncControls = try unboxOpaque(
                    element, as: NSFileManagerSupportedSyncControls.self, typeName: "NSFileManagerSupportedSyncControls"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NSFileManagerSupportedSyncControls")
        }
        #endif
        return d
    }()
}
