// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let uRLFileProtection: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["var URLFileProtection.hashValue: Int"] = .computed { receiver in
        let recv: URLFileProtection = try unboxOpaque(receiver, as: URLFileProtection.self, typeName: "URLFileProtection")
        return .int(recv.hashValue)
    }
    d["static let URLFileProtection.none"] = .staticValue(boxOpaque(URLFileProtection.none, typeName: "URLFileProtection"))
    d["static let URLFileProtection.complete"] = .staticValue(boxOpaque(URLFileProtection.complete, typeName: "URLFileProtection"))
    d["static let URLFileProtection.completeUnlessOpen"] = .staticValue(boxOpaque(URLFileProtection.completeUnlessOpen, typeName: "URLFileProtection"))
    d["static let URLFileProtection.completeUntilFirstUserAuthentication"] = .staticValue(boxOpaque(URLFileProtection.completeUntilFirstUserAuthentication, typeName: "URLFileProtection"))
    d["init URLFileProtection(rawValue:)"] = .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init URLFileProtection(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(URLFileProtection(rawValue: try unboxString(args[0])), typeName: "URLFileProtection")
    }
        #endif
        return d
    }()
}
