// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let propertyListDecoder: [String: Bridge] = {
        var d: [String: Bridge] = [:]
        #if canImport(Darwin)
    d["init PropertyListDecoder()"] = .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init PropertyListDecoder(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(PropertyListDecoder(), typeName: "PropertyListDecoder")
    }
        #endif
        return d
    }()
}
