// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let durationUnitsFormatStyle: [String: Bridge] = [
    "var Duration.UnitsFormatStyle.locale": .computed { receiver in
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "var Duration.UnitsFormatStyle.maximumUnitCount": .computed { receiver in
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        if let _v = recv.maximumUnitCount {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var Duration.UnitsFormatStyle.hashValue": .computed { receiver in
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        return .int(recv.hashValue)
    },
    "func Duration.UnitsFormatStyle.format()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Duration.UnitsFormatStyle.format: expected 1 argument(s), got \(args.count)")
        }
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        return .string(recv.format(try unboxOpaque(args[0], as: Duration.self, typeName: "Duration")))
    },
    "func Duration.UnitsFormatStyle.locale()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Duration.UnitsFormatStyle.locale: expected 1 argument(s), got \(args.count)")
        }
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        return boxOpaque(recv.locale(try unboxOpaque(args[0], as: Locale.self, typeName: "Locale")), typeName: "Duration.UnitsFormatStyle")
    },
    "func Duration.UnitsFormatStyle.discreteInput()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Duration.UnitsFormatStyle.discreteInput: expected 1 argument(s), got \(args.count)")
        }
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        if let _v = recv.discreteInput(before: try unboxOpaque(args[0], as: Duration.self, typeName: "Duration")) {
            return .optional(boxOpaque(_v, typeName: "Duration"))
        }
        return .optional(nil)
    },
    ]
}
