#if canImport(Darwin)
// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    // `JobPriority(_:)` has no public initializer on either macOS or iOS,
    // so the bridge generator's emitted init is unbuildable. Leave the
    // bucket empty until the symbol-graph filter learns to skip
    // initializers without accessible designated inits.
    nonisolated(unsafe) static let jobPriority: [String: Bridge] = [:]
}
#endif
