#if canImport(Darwin)
// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let presentationIntentIntentType: [String: Bridge] = [
    "var PresentationIntent.IntentType.identity: Int": .computed { receiver in
        let recv: PresentationIntent.IntentType = try unboxOpaque(receiver, as: PresentationIntent.IntentType.self, typeName: "PresentationIntent.IntentType")
        return .int(recv.identity)
    },
    "var PresentationIntent.IntentType.debugDescription: String": .computed { receiver in
        let recv: PresentationIntent.IntentType = try unboxOpaque(receiver, as: PresentationIntent.IntentType.self, typeName: "PresentationIntent.IntentType")
        return .string(recv.debugDescription)
    },
    "var PresentationIntent.IntentType.hashValue: Int": .computed { receiver in
        let recv: PresentationIntent.IntentType = try unboxOpaque(receiver, as: PresentationIntent.IntentType.self, typeName: "PresentationIntent.IntentType")
        return .int(recv.hashValue)
    },
    ]
}
#endif
