// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let processInfo: [String: Bridge] = [
    "static let ProcessInfo.processInfo": .staticValue(boxOpaque(ProcessInfo.processInfo, typeName: "ProcessInfo")),
    "var ProcessInfo.hostName: String": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .string(recv.hostName)
    },
    "var ProcessInfo.processName: String": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .string(recv.processName)
    },
        "set var ProcessInfo.processName: String": .setter { receiver, newValue in
            let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
            recv.processName = try unboxString(newValue)
        },
    "var ProcessInfo.globallyUniqueString: String": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .string(recv.globallyUniqueString)
    },
    "var ProcessInfo.operatingSystemVersionString: String": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .string(recv.operatingSystemVersionString)
    },
    "var ProcessInfo.processorCount: Int": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .int(recv.processorCount)
    },
    "var ProcessInfo.activeProcessorCount: Int": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .int(recv.activeProcessorCount)
    },
    "var ProcessInfo.systemUptime: Double": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .double(recv.systemUptime)
    },
    "var ProcessInfo.isLowPowerModeEnabled: Bool": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .bool(recv.isLowPowerModeEnabled)
    },
    "var ProcessInfo.isMacCatalystApp: Bool": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .bool(recv.isMacCatalystApp)
    },
    "var ProcessInfo.isiOSAppOnMac: Bool": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .bool(recv.isiOSAppOnMac)
    },
    "static let ProcessInfo.thermalStateDidChangeNotification": .staticValue(boxOpaque(ProcessInfo.thermalStateDidChangeNotification, typeName: "NSNotification.Name")),
    ]
}
