// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation

extension FoundationBridges {
    nonisolated(unsafe) static let jSONSerializationReadingOptions: [String: Bridge] = [
    "init JSONSerialization.ReadingOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init JSONSerialization.ReadingOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(JSONSerialization.ReadingOptions(), typeName: "JSONSerialization.ReadingOptions")
    },
    "var JSONSerialization.ReadingOptions.isEmpty": .computed { receiver in
        let recv: JSONSerialization.ReadingOptions = try unboxOpaque(receiver, as: JSONSerialization.ReadingOptions.self, typeName: "JSONSerialization.ReadingOptions")
        return .bool(recv.isEmpty)
    },
    "static let JSONSerialization.ReadingOptions.mutableContainers": .staticValue(boxOpaque(JSONSerialization.ReadingOptions.mutableContainers, typeName: "JSONSerialization.ReadingOptions")),
    "static let JSONSerialization.ReadingOptions.mutableLeaves": .staticValue(boxOpaque(JSONSerialization.ReadingOptions.mutableLeaves, typeName: "JSONSerialization.ReadingOptions")),
    "static let JSONSerialization.ReadingOptions.fragmentsAllowed": .staticValue(boxOpaque(JSONSerialization.ReadingOptions.fragmentsAllowed, typeName: "JSONSerialization.ReadingOptions")),
    "static let JSONSerialization.ReadingOptions.json5Allowed": .staticValue(boxOpaque(JSONSerialization.ReadingOptions.json5Allowed, typeName: "JSONSerialization.ReadingOptions")),
    "static let JSONSerialization.ReadingOptions.topLevelDictionaryAssumed": .staticValue(boxOpaque(JSONSerialization.ReadingOptions.topLevelDictionaryAssumed, typeName: "JSONSerialization.ReadingOptions")),
    "static let JSONSerialization.ReadingOptions.allowFragments": .staticValue(boxOpaque(JSONSerialization.ReadingOptions.allowFragments, typeName: "JSONSerialization.ReadingOptions")),
    ]
}
