#!/usr/bin/env bash
# Refresh Resources/foundation-symbols-scl.txt — the cross-platform
# symbol set used by the bridge generator to decide which entries are
# safe on Linux/Windows. Pass the path to a swift-corelibs-foundation
# checkout; the script parses its public API surface with SwiftSyntax
# (via the SCLSymbolExtractor target) and writes the result to the
# checked-in extract.
#
# Refresh on demand — typically when scl-foundation gets a release
# that changes the cross-platform Foundation surface, or when a
# generator regen surfaces "missing on Linux" errors that should
# actually be cross-platform.
set -euo pipefail

cd "$(dirname "$0")/.."

SCL_PATH="${1:-}"
if [[ -z "$SCL_PATH" ]]; then
  cat <<EOF >&2
usage: $0 <path-to-swift-corelibs-foundation>

Clone scl-foundation first if you don't have one:
  git clone https://github.com/swiftlang/swift-corelibs-foundation.git
EOF
  exit 2
fi

if [[ ! -d "$SCL_PATH/Sources/Foundation" ]]; then
  echo "error: $SCL_PATH does not look like a swift-corelibs-foundation tree" >&2
  exit 1
fi

OUTPUT="Resources/foundation-symbols-scl.txt"

# Capture the scl-foundation revision so `git log` on the extract
# tells us where it came from.
SCL_REV="unknown"
if [[ -d "$SCL_PATH/.git" ]]; then
  SCL_REV="$(cd "$SCL_PATH" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
fi

echo "extracting public symbols from scl-foundation (rev: $SCL_REV)..."

# Build args: scl-foundation + the swift-foundation checkout it
# depends on. swift-foundation owns FoundationEssentials/Internat-
# ionalization (JSON, Date/Number formatting, Locale, …) — the bulk
# of the cross-platform Foundation surface lives there now.
EXTRACT_ARGS=(
  --source "$SCL_PATH/Sources/Foundation"
  --source "$SCL_PATH/Sources/FoundationNetworking"
  --source "$SCL_PATH/Sources/FoundationXML"
)
SF_PATH="$SCL_PATH/.build/checkouts/swift-foundation"
if [[ -d "$SF_PATH/Sources/FoundationEssentials" ]]; then
  EXTRACT_ARGS+=(
    --source "$SF_PATH/Sources/FoundationEssentials"
    --source "$SF_PATH/Sources/FoundationInternationalization"
  )
  SF_REV="unknown"
  if [[ -d "$SF_PATH/.git" ]] || [[ -f "$SF_PATH/../../workspace-state.json" ]]; then
    SF_REV="$(cd "$SF_PATH" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
  fi
  echo "  + swift-foundation (rev: $SF_REV)"
else
  echo "  warning: $SF_PATH not found — run 'swift build' inside scl-foundation first"
  echo "           to fetch the swift-foundation dependency."
fi

swift run -q SCLSymbolExtractor \
  "${EXTRACT_ARGS[@]}" \
  --output "$OUTPUT.tmp"

# Prepend a header with provenance.
{
  echo "# AUTO-GENERATED by Tools/refresh-scl-symbols.sh from"
  echo "# swift-corelibs-foundation @ $SCL_REV"
  echo "#"
  echo "# Used by BridgeGeneratorTool to classify each Apple-side bridge"
  echo "# entry as cross-platform or Apple-only. Format: one Type.member"
  echo "# per line, with an optional UNAVAILABLE marker when scl declares"
  echo "# the symbol but marks it @available(*, unavailable)."
  echo
  cat "$OUTPUT.tmp"
} > "$OUTPUT"
rm -f "$OUTPUT.tmp"

LINES=$(wc -l < "$OUTPUT")
echo "wrote $LINES lines to $OUTPUT"
